class_name Loc
extends RefCounted

## Lightweight runtime localization facade. Gameplay code only references keys;
## this can later be swapped for Godot Translation resources without touching it.

const SUPPORTED_LOCALES := ["ru", "en"]

const STRINGS := {
	"ru": {
		"INSPECT_ARACHNID_ABILITY": "Двойная атака: 2 удара, откат 15.",
		"INSPECT_BONE_CROSSBOWMAN_ABILITY": "Выстрел: подготовка 2, простой 1, откат 3.",
		"INSPECT_SLAG_SMITH_ABILITY": "Замах 1 ход: урон 5 по отмеченной клетке, откат 6.",
		"INVENTORY_BACKPACK_REMOVAL": "Первое снятие: до −200 ходов обоих эффектов.",
		"INVENTORY_LAMP_HEARING": "Не открывает «Уши».",
		"MSG_ENEMY_PREPARING": "%s готовит сильную атаку. Ходов до удара: %d.",
		"INSPECT_PREPARATION": "Подготовка, ходов: %d",
		"INSPECT_CRYPT": "Склеп",
		"BIOME_WEAVING_CRYPTS": "Ткацкие склепы",
		"PARAM_PREPARATION": "Сытость/Отдых, ходы",
		"INVENTORY_MARK_KEEP": "Беречь",
		"INVENTORY_MARK_SALVAGE": "На разбор",
		"INVENTORY_MARKED_ONLY": "Только «На разбор»",
		"INVENTORY_KEEP_CONFIRM": "«Беречь»: подтвердите разбор одной вещи.",
		"INVENTORY_KEEP_CONFIRM_BUTTON": "Подтвердить",
		"CAMP_KETTLE": "Походный котёл",
		"CAMP_BUNK": "Тканевые нары",
		"CAMP_MURAL": "Мурал",
		"CAMP_WORKBENCH": "Верстак",
		"CAMP_WRITING_SET": "Письменные принадлежности",
		"CAMP_TEXTILE_AREA": "Ткацкий уголок",
		"CAMP_ROCKING_CHAIR": "Кресло-качалка",
		"CAMP_RECORD_PLAYER": "Проигрыватель",
		"CAMP_STORAGE_CHEST": "Сундук хранения",
		"CAMP_BUILD_KETTLE": "Котёл: дерево 6, камень 8, ткань 2",
		"CAMP_BUILD_BUNK": "Нары: дерево 8, ткань 6",
		"CAMP_BUILD_MURAL": "Мурал: 12 / 20 / 5, души 60, хвост 1",
		"CAMP_BUILD_WORKBENCH": "Верстак: бесплатно",
		"CAMP_BUILD_WRITING_SET": "Письменные принадлежности: бесплатно",
		"CAMP_BUILD_TEXTILE_AREA": "Ткацкий уголок: бесплатно",
		"CAMP_BUILD_ROCKING_CHAIR": "Кресло-качалка: дерево 30",
		"CAMP_BUILD_RECORD_PLAYER": "Проигрыватель: бесплатно",
		"CAMP_BUILD_STORAGE_CHEST": "Сундук хранения: дерево 20, камень 4, ткань 3",
		"CAMP_BUILT_KETTLE": "Походный котёл построен",
		"CAMP_BUILT_BUNK": "Тканевые нары построены",
		"CAMP_BUILT_MURAL": "Мурал — победа над Минотавром",
		"CAMP_BUILT_WORKBENCH": "Верстак построен",
		"CAMP_BUILT_WRITING_SET": "Письменные принадлежности готовы",
		"CAMP_BUILT_TEXTILE_AREA": "Ткацкий уголок готов",
		"CAMP_BUILT_ROCKING_CHAIR": "Кресло-качалка построено",
		"CAMP_BUILT_RECORD_PLAYER": "Проигрыватель установлен",
		"CAMP_BUILT_STORAGE_CHEST": "Сундук хранения построен",
		"CAMP_KETTLE_DESC": "При выходе можно потратить 1 еду: +100 ходов Сытости.",
		"CAMP_BUNK_DESC": "При подготовленном выходе: +100 ходов Отдыха.",
		"CAMP_CAMPFIRE_DESC": "Постоянно +1 уровень души; открывает походный котёл.",
		"CAMP_CRUSHER_DESC": "Открывает разбор несвязанных предметов на материалы.",
		"CAMP_WHETSTONE_DESC": "Открывает улучшение оружия до +3 за ресурсы.",
		"CAMP_RITUAL_TABLE_DESC": "Открывает привязку одного экземпляра предмета за 25 доступных душ.",
		"CAMP_MURAL_DESC": "Граффити победы. Дерево 12, камень 20, ткань 5, сохранённые души 60, Хвост Минотавра 1. Постоянно +1 уровень души.",
		"CAMP_WORKBENCH_DESC": "Бесплатный рабочий стол. Открывает письменные принадлежности; отдельной услуги не даёт.",
		"CAMP_WRITING_SET_DESC": "Старые чернила и бумага. Требует верстак; отдельной услуги не даёт.",
		"CAMP_TEXTILE_AREA_DESC": "Место для починки ткани. Бесплатно; отдельной услуги не даёт.",
		"CAMP_ROCKING_CHAIR_DESC": "Скелет сделал это кресло для себя. Оно укрепляет его личность и душу, как Мурал: постоянно +1 уровень души.",
		"CAMP_RECORD_PLAYER_DESC": "Старый механический проигрыватель. Бесплатно; отдельной услуги не даёт.",
		"CAMP_STORAGE_CHEST_DESC": "Хранит переносимые предметы между вылазками. Содержимое не теряется при смерти.",
		"CAMP_BUILD_BUTTON": "Стройка",
		"CAMP_BUILD_TITLE": "СТРОЙКА",
		"CAMP_BUILD_CLOSE": "Закрыть [Esc / B]",
		"CAMP_BUILD_FREE": "Бесплатно",
		"CAMP_BUILD_STATUS_BUILT": "Построено",
		"CAMP_BUILD_STATUS_REQUIRES": "Требуется: %s",
		"CAMP_BUILD_STATUS_HIDDEN": "Скрыто",
		"CAMP_BUILD_STATUS_AVAILABLE": "Доступно",
		"CAMP_BUILD_STATUS_INSUFFICIENT": "Недостаточно ресурсов",
		"CAMP_BUILD_ACTION": "Построить",
		"CAMP_BUILD_PRICE": "Цена: %s",
		"CAMP_BUILD_PREREQUISITE": "Сначала постройте: %s.",
		"RESOURCE_WOOD": "Древесина",
		"RESOURCE_STONE": "Камень",
		"RESOURCE_CLOTH": "Ткань",
		"RESOURCE_BANKED_SOULS": "Сохранённые души",
		"RESOURCE_MINOTAUR_TAIL": "Хвост Минотавра",
		"CAMP_KETTLE_SELECT": "Подготовить котёл: 1 еда, +100 Сытости",
		"CAMP_KETTLE_NEEDS_FOOD": "Для выбранной подготовки нужна 1 еда.",
		"CAMP_PREPARATION_DESC": "Возвращение восстанавливает HP и сытость. Временные эффекты выдаются при выходе. Рюкзак даёт +200 ходов; первое снятие убирает этот бонус.",
		"CAMP_START_TOOLTIP": "Начать вылазку. Возвращение восстанавливает HP и сытость; временные эффекты выдаются при выходе.",
		"MSG_MINOTAUR_TAIL": " Получен Хвост Минотавра — постоянный трофей для Мурала.",
		"TROPHY_MINOTAUR_TAIL": "Хвост Минотавра",
		"ITEM_RUSTY_SABRE": "Ржавая сабля",
		"ITEM_SHORT_CROSSBOW": "Короткий арбалет",
		"ITEM_BONE_BUCKLER": "Костяной баклер",
		"ITEM_GRAVEDIGGERS_LAMP": "Лампа могильщика",
		"ITEM_WATCHMANS_CAP": "Шапка сторожа",
		"ITEM_ARCHIVISTS_MASK": "Маска архивиста",
		"ITEM_WANDERERS_GAMBESON": "Стёганка странника",
		"ITEM_LAMELLAR_VEST": "Ламельный жилет",
		"ITEM_SCOUTS_TROUSERS": "Штаны лазутчика",
		"ITEM_HEAVY_LEG_WRAPS": "Плотные обмотки",
		"ITEM_PILGRIMS_BOOTS": "Башмаки паломника",
		"ITEM_AIMING_RING": "Кольцо прицела",
		"ITEM_THICKBLOOD_RING": "Кольцо плотной крови",
		"ITEM_EXPEDITION_BACKPACK": "Походный рюкзак",
		"ENEMY_BLIND_SCAVENGER": "Слепой падальщик",
		"ENEMY_ARACHNID": "Арахнид",
		"ENEMY_BONE_CROSSBOWMAN": "Костяной арбалетчик",
		"ENEMY_SLAG_SMITH": "Шлаковый кузнец",
		"GLYPH_BLIND_SCAVENGER": "П",
		"GLYPH_ARACHNID": "А",
		"GLYPH_BONE_CROSSBOWMAN": "К",
		"GLYPH_SLAG_SMITH": "Ш",
		"ATTR_STRENGTH": "Сила", "ATTR_AGILITY": "Ловкость", "ATTR_PERCEPTION": "Восприятие",
		"ATTR_VITALITY": "Живучесть", "ATTR_WISDOM": "Мудрость",
		"FORM_SKELETON": "Скелет", "FORM_ZOMBIE": "Зомби", "FORM_GHOUL": "Гуль",
		"FORM_REVENANT": "Ревенант", "FORM_ALMOST_HUMAN": "Почти человек",
		"TRAIT_SKELETON": "Неуязвим к яду, хрупок в ближнем бою",
		"TRAIT_ZOMBIE": "Больше здоровья, но тело ещё неповоротливо",
		"TRAIT_GHOUL": "Сильные атаки и доступ к снаряжению для кистей",
		"TRAIT_REVENANT": "Управляет реликвиями и удерживает больше силы душ",
		"TRAIT_ALMOST_HUMAN": "Может использовать полный набор человеческого снаряжения",
		"SLOT_WEAPON": "Оружие", "SLOT_CHARM": "Талисман", "SLOT_ARMOR": "Броня",
		"SLOT_HANDS": "Кисти", "SLOT_RELIC": "Реликвия", "SLOT_OFFHAND": "Вторая рука",
		"SLOT_RIGHT_HAND": "Основная рука", "SLOT_LEFT_HAND": "Вспомогательная рука",
		"SLOT_FEET": "Обувь", "SLOT_BODY": "Тело", "SLOT_LEGS": "Поножи",
		"SLOT_HEAD": "Шлем", "SLOT_TALISMAN": "Талисман", "SLOT_RING_1": "Кольцо 1",
		"SLOT_RING_2": "Кольцо 2", "SLOT_BACK": "Рюкзак", "SLOT_JACKET": "Плащ",
		"CATEGORY_WEAPON": "Оружие", "CATEGORY_OFFHAND": "Вспомогательная рука",
		"CATEGORY_FEET": "Обувь", "CATEGORY_BODY": "Тело", "CATEGORY_LEGS": "Поножи",
		"CATEGORY_HANDS": "Руки", "CATEGORY_HEAD": "Шлемы", "CATEGORY_TALISMAN": "Талисманы",
		"CATEGORY_RING": "Кольца", "CATEGORY_BACK": "Рюкзак",
		"ITEM_BONE_KNIFE": "Костяной нож", "ITEM_GRAVE_MACE": "Могильная булава",
		"ITEM_BONE_BOW": "Костяной лук",
		"ITEM_OLD_CLAYMORE": "Старый клеймор",
		"ITEM_OLD_CLAYMORE_DESC": "Потёртый длинный двуручный меч.",
		"ITEM_SOUL_LOCKET": "Медальон ловца", "ITEM_ROTTING_MAIL": "Сшитый панцирь",
		"ITEM_LEATHER_GLOVES": "Кожаные перчатки", "ITEM_HOLLOW_LANTERN": "Пустотный фонарь",
		"ITEM_PILGRIM_SHIELD": "Щит паломника",
		"ITEM_UNEXPECTEDLY_COMFORTABLE_JACKET": "Уютный пиджак",
		"ITEM_UNEXPECTEDLY_COMFORTABLE_JACKET_DESC": "+1 Уровень души",
		"CAMP_CRUSHER": "Дробилка", "CAMP_WHETSTONE": "Точильный камень",
		"CAMP_RITUAL_TABLE": "Ритуальный стол", "CAMP_CAMPFIRE": "Костёр",
		"MSG_TWO_HANDED_OFFHAND_BLOCKED": "Двуручное оружие занимает обе руки. Вспомогательная рука недоступна.",
		"WEAPON_CLASS_ONE_HANDED": "Одноручное",
		"WEAPON_CLASS_TWO_HANDED": "Двуручное",
		"WEAPON_CLASS_RANGED_TWO_HANDED": "Стрелковое двуручное",
		"WEAPON_GHOST_TOOLTIP": "Эта рука занята двуручным оружием из основной руки. Выбор перенаправляется в основную руку.",
		"ENEMY_GRAVE_RAT": "Могильная крыса", "ENEMY_HOLLOW_GUARD": "Пустой страж",
		"ENEMY_SOUL_LEECH": "Душеед", "ENEMY_SKELETAL_ARCHER": "Скелет-лучник",
		"ENEMY_MINOTAUR": "Минотавр",
		"GLYPH_GRAVE_RAT": "к", "GLYPH_HOLLOW_GUARD": "с", "GLYPH_SOUL_LEECH": "д",
		"GLYPH_SKELETAL_ARCHER": "л", "GLYPH_MINOTAUR": "М", "GLYPH_PLAYER": "И",
		"GLYPH_FORM_SKELETON": "С", "GLYPH_FORM_ZOMBIE": "З", "GLYPH_FORM_GHOUL": "Г",
		"GLYPH_FORM_REVENANT": "Р", "GLYPH_FORM_ALMOST_HUMAN": "Ч",
		"GLYPH_START": "S", "GLYPH_BASE": "Б",
		"GLYPH_CHEST": "▣",
		"BTN_START": "Начать вылазку", "BTN_CHARACTER_ACTION": "Перс. [E]",
		"BTN_INTERACT": "Действ.", "BTN_ASCEND": "Вверх [G]",
		"BTN_WAIT_ONE": "1 ход [T]", "BTN_WAIT_MANY": "%d ходов [T]",
		"WAIT_CYCLE_HINT": "Переключить ожидание: 1 → 10 → 100 ходов",
		"BTN_AUTO_EXPLORE": "Авто [X]", "BTN_AUTO_EXPLORE_STOP": "Стоп [X]",
		"BTN_ATTACK": "Атака [F]", "BTN_MAGIC": "Магия [Q]", "BTN_MAGIC_READY": "Стрела [Q]",
		"BTN_CAMP": "Привал [R]",
		"BTN_UPGRADE": "Укрепить костяное убежище", "BTN_CHARACTER": "Персонаж [E]",
		"BTN_CONTINUE": "Продолжить", "BTN_FINISH_CREATION": "Завершить создание",
		"BTN_BACK": "Вернуться [Esc]", "BTN_LANGUAGE": "Язык: %s", "BTN_MENU": "Меню",
		"BTN_MAIN_MENU": "Главное меню",
		"BTN_NEW_GAME": "Начать новую игру", "BTN_NEW_GAME_CONFIRM": "Точно начать заново?",
		"BTN_EXIT": "Выйти из игры", "BTN_EXIT_CONFIRM": "Точно выйти?",
		"SAVE_MENU_TITLE": "ALMSTH", "SAVE_MENU_SUBTITLE": "Выберите, чью историю продолжить.",
		"STAGE1C_BUILD_STATUS": "Этап 1C · Локальная сборка",
		"SAVE_MENU_LOAD_SUBTITLE": "Сохранённые герои — новые записи сверху",
		"SAVE_MENU_EMPTY_SUBTITLE": "Сохранений нет: создайте нового персонажа.",
		"SAVE_MENU_CONTINUE": "Продолжить последнее", "SAVE_MENU_RESUME": "Продолжить",
		"SAVE_MENU_NEW": "Новый персонаж",
		"SAVE_MENU_LOAD": "Загрузить сохранение", "SAVE_MENU_BACK": "Назад [Esc / B]",
		"SAVE_MENU_SETTINGS": "Настройки", "SAVE_MENU_EXIT": "Выйти из игры",
		"SAVE_MENU_EMPTY": "Сохранений пока нет.", "SAVE_MENU_UNKNOWN_DATE": "дата неизвестна",
		"SAVE_MENU_ROW": "%s  ·  %s  ·  всего душ: %d",
		"SAVE_MENU_ROW_META": "%s  ·  всего душ: %d",
		"SAVE_MENU_INCOMPATIBLE_NAME": "Несовместимое сохранение",
		"SAVE_MENU_INCOMPATIBLE_META": "Версия %d · загрузка недоступна",
		"SAVE_MENU_INCOMPATIBLE_TOOLTIP": "%s · версия %d несовместима. Сохранение можно только удалить.",
		"SAVE_MENU_CORRUPT_NAME": "Повреждённое сохранение",
		"SAVE_MENU_CORRUPT_META": "Повреждённая семья · загрузка недоступна",
		"SAVE_MENU_CORRUPT_TOOLTIP": "%s · семья повреждена (ошибка %d). Она не изменена автоматически; оставьте игру открытой и сообщите код, если нужна помощь.",
		"SAVE_MENU_DELETE_TOOLTIP": "Удалить сохранение: %s",
		"SAVE_MENU_DELETE_TITLE": "Удалить сохранение?",
		"SAVE_MENU_DELETE_BODY": "Персонаж: %s\nСохранено: %s\n\nЭто действие необратимо.",
		"SAVE_MENU_DELETE_ACTIVE_WARNING": "Текущая игра останется в памяти. После продолжения новое сохранение будет создано отдельно.",
		"SAVE_MENU_DELETE_NO": "Нет, оставить",
		"SAVE_MENU_DELETE_YES": "Да, удалить",
		"SAVE_MENU_DELETE_ERROR": "Не удалось удалить сохранение (ошибка %d). Проверьте список и попробуйте снова.",
		"SAVE_MENU_PREVIOUS": "← Раньше", "SAVE_MENU_NEXT": "Позже →", "SAVE_MENU_PAGE": "Страница %d / %d",
		"SAVE_POLICY_OVERWRITE": "Перезаписывать один слот этого персонажа",
		"SAVE_POLICY_HINT": "Выключите, чтобы сохранять историю возвращений отдельными снимками.",
		"MSG_SAVE_FAILED": "Не удалось сохранить игру (ошибка %d).",
		"MSG_LOAD_FAILED": "Не удалось загрузить выбранное сохранение.",
		"MSG_SAVE_OCCUPIED_INCOMPATIBLE": "Не удалось сохранить игру: выбранная занятая семья несовместима с безопасной перезаписью (ошибка %d). Семья не изменена, текущая игра остаётся в памяти. Не закрывайте игру; выберите заведомо исправную запись или сообщите этот код ошибки.",
		"MSG_SAVE_CORRUPT_FAMILY": "Не удалось сохранить игру: выбранная семья сохранений повреждена или несовместима (ошибка %d). Семья не изменена, текущая игра остаётся в памяти. Не закрывайте игру; выбирайте только заведомо исправную запись или сообщите этот код ошибки.",
		"MSG_SAVE_INVALID_LIVE_SNAPSHOT": "Не удалось сохранить игру: текущее состояние не прошло строгую проверку (ошибка %d). Файлы сохранения не изменены, игра остаётся в памяти. Не закрывайте игру и сообщите этот код ошибки.",
		"MSG_SAVE_WRITE_VERIFICATION_FAILED": "Не удалось сохранить игру: временная запись не прошла проверку (ошибка %d). Семья сохранений не изменена, текущая игра остаётся в памяти. Не закрывайте игру и сообщите этот код ошибки.",
		"MSG_LOAD_CORRUPT_FAMILY": "Не удалось загрузить повреждённую семью сохранений (ошибка %d). Файлы не изменены, текущий сеанс остался прежним. Выберите заведомо исправную запись или сообщите этот код ошибки.",
		"SETTINGS_TITLE": "Настройки",
		"BTN_SETTINGS_CLOSE": "Вернуться [Esc]", "SETTINGS_WINDOWED": "Режим: в окне",
		"SETTINGS_FULLSCREEN": "Режим: полный экран",
		"SETTINGS_INPUT_SUMMARY": "Назначения клавиатуры и геймпада можно изменить.",
		"SETTINGS_SOUND_ON": "Звук: включён", "SETTINGS_SOUND_OFF": "Звук: выключен",
		"SETTINGS_BACKGROUND_VOLUME": "Фон: %d%%", "SETTINGS_ACTIONS_VOLUME": "Действия: %d%%",
		"SETTINGS_ZOOM": "Масштаб: %s · %d px", "SETTINGS_ZOOM_MAP": "Карта",
		"SETTINGS_ZOOM_TACTICS": "Тактика", "SETTINGS_ZOOM_DETAILS": "Детали",
		"SETTINGS_ZOOM_DESC": "Меняет только размер клеток и камеры; правила подземелья не меняются. В подземелье: + приблизить, − отдалить.",
		"SETTINGS_AUTO_SPEED": "Скорость автоперемещения: %s",
		"SETTINGS_AUTO_SPEED_NORMAL": "Нормально", "SETTINGS_AUTO_SPEED_FASTER": "Быстрее",
		"SETTINGS_AUTO_SPEED_VERY_FAST": "Очень быстро", "SETTINGS_AUTO_SPEED_MAXIMUM": "Максимально",
		"SETTINGS_AUTO_SPEED_DESC": "Ускоряет автоисследование и путь к лестнице. Не меняет стоимость хода или скорость ручного движения.",
		"BTN_CONTROLS": "Настроить управление",
		"CONTROLS_TITLE": "Управление",
		"CONTROLS_SUBTITLE": "Выберите назначение, затем нажмите новую клавишу или кнопку геймпада.",
		"CONTROLS_ACTION_HEADER": "Действие", "CONTROLS_KEYBOARD_HEADER": "Клавиатура",
		"CONTROLS_GAMEPAD_HEADER": "Геймпад", "CONTROLS_BACK": "Вернуться [Esc / B]",
		"CONTROLS_RESET": "Сбросить по умолчанию", "CONTROLS_RESET_CONFIRM": "Подтвердить сброс",
		"CONTROLS_RESET_WARNING": "Повторное нажатие восстановит все стандартные назначения. Esc / B — отменить.",
		"CONTROLS_RESET_DONE": "Стандартные назначения восстановлены.",
		"CONTROLS_NOT_ASSIGNED": "Не назначено",
		"CONTROLS_WAIT_KEYBOARD": "Ожидание клавиши… Esc — отменить.",
		"CONTROLS_WAIT_GAMEPAD": "Ожидание кнопки или направления геймпада… B — отменить.",
		"CONTROLS_WRONG_DEVICE": "Ожидается ввод с устройства: %s.",
		"CONTROLS_CONFLICT": "%s уже назначено: %s. Enter / A — перенести сюда · Esc / B — отменить.",
		"CONTROLS_CONFLICT_CONFIRM": "Перенести назначение",
		"CONTROLS_CONFLICT_CANCEL": "Оставить как есть",
		"CONTROLS_APPLIED": "%s назначено действию «%s».",
		"CONTROLS_CANCELLED": "Изменение отменено.",
		"CONTROLS_NAV_HINT": "Стрелки / D-pad — выбор · Enter / A — изменить · Esc / B — назад",
		"INPUT_ACTION_MOVE_UP": "Движение вверх", "INPUT_ACTION_MOVE_DOWN": "Движение вниз",
		"INPUT_ACTION_MOVE_LEFT": "Движение влево", "INPUT_ACTION_MOVE_RIGHT": "Движение вправо",
		"INPUT_ACTION_ATTACK": "Основная атака", "INPUT_ACTION_CAST_SPELL": "Активный слот 1",
		"INPUT_ACTION_WAIT": "Ждать ход", "INPUT_ACTION_AUTO_EXPLORE": "Исследовать этаж",
		"INPUT_ACTION_CAMP": "Привал",
		"INPUT_ACTION_ASCEND": "Путь к лестнице", "INPUT_ACTION_INTERACT": "Взаимодействие",
		"INPUT_ACTION_CHARACTER": "Лист персонажа", "INPUT_ACTION_MENU": "Меню / назад",
		"INPUT_KEY_SPACE": "Пробел", "INPUT_KEY_ENTER": "Enter", "INPUT_KEY_ESCAPE": "Esc",
		"INPUT_KEY_TAB": "Tab", "INPUT_KEY_BACKSPACE": "Backspace",
		"INPUT_PAD_BACK": "Назад", "INPUT_PAD_START": "Start", "INPUT_PAD_BUTTON": "Кнопка %d",
		"INPUT_DPAD_DIRECTION": "Крестовина %s", "INPUT_LEFT_STICK_DIRECTION": "Левый стик %s",
		"INPUT_RIGHT_STICK_DIRECTION": "Правый стик %s", "INPUT_PAD_AXIS": "Ось %d %s",
		"EXPEDITION_CHOICE_TITLE": "Откуда начать вылазку?",
		"EXPEDITION_CHOICE_DESC": "Верёвка ведёт на лучший уровень, с которого вы уже возвращались. Начало восхождения позволит заново собрать силы.",
		"BTN_ASCEND_ROPE": "Подняться по верёвке — уровень %d",
		"BTN_ASCEND_ROPE_LOCKED": "Верёвка ещё не закреплена",
		"BTN_ASCEND_BEGINNING": "Начать восхождение с %d-го уровня",
		"TITLE_NAME_CREATION": "Создание персонажа — имя",
		"TITLE_STAT_CREATION": "Создание персонажа — структура души",
		"CREATION_STEP_NAME": "Шаг 1 / 2 · Пол и имя",
		"CREATION_STEP_STATS": "Шаг 2 / 2 · Характеристики",
		"CREATION_POINTS_REMAIN": "Сначала распределите все свободные очки.",
		"NAME_PROMPT": "Введите имя персонажа", "NAME_PLACEHOLDER": "Введите имя",
		"SEX_FEMALE": "Женский", "SEX_MALE": "Мужской",
		"SEX_CHOICE_HINT": "Пол: %s. Меняет образы в листе персонажа и на карте.",
		"NAME_EMPTY": "Имя не может быть пустым.", "FREE_POINTS": "Свободных очков: %d",
		"SKELETON_PARAMETERS": "Параметры",
		"PARAM_DAMAGE": "Урон", "PARAM_ACCURACY": "Точность", "PARAM_HP": "HP",
		"PARAM_DODGE": "Уклонение", "PARAM_MANA": "Мана", "PARAM_MANA_REGENERATION": "Регенерация маны",
		"PARAM_SPELL_POWER": "Сила заклинаний", "PARAM_REGENERATION": "Регенерация",
		"PARAM_RANGED_DAMAGE": "Дальний урон", "PARAM_RANGED_RANGE": "Дальность стрельбы",
		"PARAM_VISION": "Обзор", "PRIMARY_ATTRIBUTES": "ОСНОВНЫЕ ХАРАКТЕРИСТИКИ",
		"PARAMETERS": "ПАРАМЕТРЫ", "EQUIPMENT": "СНАРЯЖЕНИЕ", "FORM_TRAIT": "ОСОБЕННОСТЬ ФОРМЫ",
		"MSG_AWAKENS": "%s пробуждается у Костяного убежища.",
		"MSG_CHECKPOINT": "Активирован костяной якорь %d-го уровня.",
		"MSG_ENTER_FLOOR": "Вы вошли на %d-й уровень.",
		"MSG_SAFE_RETURN": "Безопасное возвращение. В хранилище доставлено душ: %d.",
		"MSG_NOTHING_TO_USE": "Здесь не с чем взаимодействовать. Ищите Колыбель, лестницу или путь на базу.",
		"MSG_BASE_UPGRADED": "Костяное убежище улучшено до уровня %d. Максимум здоровья вырос.",
		"MSG_UPGRADE_NEEDS": "Для улучшения нужно душ: %d.",
		"MSG_WAIT": "Вы замираете и позволяете врагам сделать ход.",
		"MSG_WAIT_COMPLETED": "Ожидание завершено: %d ходов.",
		"MSG_WAIT_INTERRUPTED": "Ожидание прервано через %d ходов: замечен враг.",
		"MSG_WAIT_INTERRUPTED_HP": "Ожидание прервано через %d ходов: здоровье начало снижаться.",
		"MSG_WAIT_INTERRUPTED_RANGED": "Ожидание прервано через %d ходов: рядом пролетела стрела.",
		"MSG_WAIT_INTERRUPTED_HEARING": "Ожидание прервано через %d ходов: услышан шум.",
		"MSG_HEARING_MOVEMENT": "Рядом слышится движение.",
		"MSG_HEARING_HIDDEN_ATTACK": "Атака пришла из темноты.",
		"MSG_EXPLORE_ENEMY": "Исследование прервано: замечен враг.",
		"MSG_EXPLORE_COMPLETE": "Все доступные участки этажа исследованы.",
		"MSG_EXPLORE_CANCELLED": "Автоматическое исследование остановлено.",
		"MSG_EXPLORE_INTERRUPTED": "Исследование прервано: путь изменился.",
		"MSG_ASCEND_LOCKED": "Сначала найдите лестницу наверх.",
		"MSG_EXIT_DISCOVERED": "Вы обнаружили лестницу наверх.",
		"MSG_ASCEND_NO_PATH": "До лестницы не удалось построить безопасный путь.",
		"MSG_ASCEND_STARTED": "Вы направляетесь к лестнице. Путь займёт %d ходов.",
		"MSG_ASCEND_ARRIVED": "Вы дошли до лестницы. Нажмите подъём ещё раз, чтобы перейти на следующий уровень.",
		"MSG_ASCEND_INTERRUPTED": "Движение к лестнице прервано.",
		"MSG_VICTORY": "Вы достигли первого уровня. За дверью — свет и вопрос: осталось ли в вас что-то человеческое?",
		"MSG_WALL": "Камень не уступает.",
		"MSG_BOSS_DOOR_LOCKED": "Тяжёлая дверь запечатана силой Минотавра.",
		"MSG_DOOR_OPENED": "Вы открываете дверь и входите в проём.",
		"INSPECT_DOOR": "Закрытая дверь комнаты",
		"INSPECT_DOOR_OPEN": "Открытая дверь комнаты",
		"MSG_BOSS_DOOR_OPEN": " Дверь за ареной открывается.",
		"MSG_PLAYER_MISS": "Промах по цели «%s» (%d против %d).",
		"MSG_ENEMY_KILLED": "%s уничтожен. Получено душ: %d.",
		"MSG_PLAYER_HIT": "Удар по цели «%s»: осталось %d здоровья.",
		"MSG_ENEMY_MISS": " %s промахивается (%d против %d).",
		"MSG_ENEMY_HIT": " %s наносит %d урона.", "MSG_ITEM_EQUIPPED": "Экипировано: %s.",
		"MSG_HIDDEN_ENEMY_MISS": " В темноте слышен промах.",
		"MSG_HIDDEN_ENEMY_HIT": " Удар из темноты наносит %d урона.",
		"MSG_RANGED_NO_TARGET": "В радиусе %d клеток нет видимой цели для выстрела.",
		"MSG_RANGED_TARGET_HIDDEN": "Выбранная цель скрыта туманом войны.",
		"MSG_RANGED_OUT_OF_RANGE": "Выбранная цель вне дальности лука (%d клеток).",
		"MSG_RANGED_LINE_BLOCKED": "Между вами и выбранной целью нет прямой линии огня.",
		"MSG_PLAYER_RANGED_MISS": "Стрела не попадает в цель «%s» (%d против %d).",
		"MSG_PLAYER_RANGED_HIT": "Стрела поражает «%s»: %d урона, осталось %d HP.",
		"MSG_PLAYER_RANGED_KILLED": "Стрела уничтожает «%s»: %d урона, получено душ %d.",
		"MSG_ENEMY_RANGED_MISS": " %s выпускает стрелу и промахивается (%d против %d).",
		"MSG_ENEMY_RANGED_HIT": " %s попадает стрелой: %d урона.",
		"MSG_HIDDEN_RANGED_MISS": " Из темноты прилетает стрела и проходит мимо.",
		"MSG_HIDDEN_RANGED_HIT": " Стрела из темноты наносит %d урона.",
		"MSG_MANA_REGENERATED": " Мана восстанавливается: +%d.",
		"MSG_MAGIC_LOCKED": "Сначала пробудите магию и изучите Магическую стрелу.",
		"MSG_MAGIC_NO_MANA": "Для Магической стрелы нужно %d маны.",
		"MSG_MAGIC_OUT_OF_RANGE": "Выбранная цель вне дальности заклинания (%d клеток).",
		"MSG_MAGIC_LINE_BLOCKED": "Между вами и выбранной целью проходит стена.",
		"MSG_MAGIC_NO_TARGET": "В радиусе %d клеток нет цели для Магической стрелы.",
		"MSG_MAGIC_HIT": "Магическая стрела поражает «%s»: %d урона, осталось %d HP.",
		"MSG_MAGIC_KILLED": "Магическая стрела уничтожает «%s»: %d урона, получено душ %d.",
		"MSG_MAGIC_RICOCHET": " Рикошет — %s",
		"MSG_ITEM_UNEQUIPPED": "Снято и возвращено в инвентарь: %s.",
		"MSG_FORM_CANNOT_EQUIP_SELECTED": "Текущая форма не может использовать этот слот.",
		"MSG_EQUIP_ITEM_MISSING": "Вещи «%s» больше нет в инвентаре.",
		"MSG_EQUIP_SLOT_CHOICE_REQUIRED": "Все подходящие слоты заняты. Сначала выберите физический слот: %s.",
		"MSG_EQUIP_SLOT_LOCKED": "«%s» нельзя надеть в слот «%s»: он недоступен форме «%s».",
		"MSG_CHEST_OPENED": "Сундук открыт: %s · дерево +%d · камень +%d.",
		"MSG_ITEM_DISMANTLED": "%s разобрано: дерево +%d · камень +%d · ткань +%d.",
		"MSG_CRUSHER_REQUIRED": "Для разбора нужна установленная дробилка на базе.",
		"MSG_WHETSTONE_REQUIRED": "Для улучшения нужен установленный точильный камень на базе.",
		"MSG_WEAPON_UPGRADED": "Улучшение удалось: оружие теперь +%d.",
		"MSG_WEAPON_DOWNGRADED": "Неудача повредила оружие: уровень снижен до +%d.",
		"MSG_WEAPON_UNCHANGED": "Улучшение не удалось, но оружие не пострадало.",
		"MSG_WEAPON_UPGRADE_RESOURCES": "Для попытки нужно %d камня, %d дерева и %d ткани.",
		"MSG_ITEM_BOUND": "%s теперь связано с героем за %d душ и сохранится после смерти.",
		"MSG_ITEM_ALREADY_BOUND": "Эта вещь уже связана с героем.",
		"MSG_ITEM_BIND_NEEDS_SOULS": "Для ритуала нужно душ: %d.",
		"MSG_RITUAL_TABLE_REQUIRED": "Привязка доступна только у построенного ритуального стола.",
		"MSG_BOUND_ITEM_CANNOT_DISMANTLE": "Связанную вещь нельзя разобрать.",
		"MSG_ITEMS_DISMANTLED_ALL": "Разобрано предметов: %d · дерево +%d · камень +%d · ткань +%d.",
		"MSG_DEATH": "Тело разрушено. Потеряно душ: %d, предметов: %d. Вы снова скелет.",
		"MSG_PATH_BASE": "Путь вниз открыт. Можно вернуться на базу и сохранить свободные души.",
		"MSG_PATH_UP": "Лестница ведёт на %d-й уровень.",
		"MSG_TILE_START": "Точка входа в уровень.", "MSG_TURN_DONE": "Ход завершён. Враги приблизились.",
		"MSG_UNKNOWN_ITEM": "Неизвестный предмет.",
		"MSG_FORM_CANNOT_USE": "Форма «%s» ещё не может использовать: %s.",
		"MSG_GAME_LOADED": "Сохранение загружено. Путешествие продолжается.",
		"MSG_NO_ADJACENT_ENEMY": "Рядом нет цели для атаки.",
		"MSG_ABILITY_SLOT_EMPTY": "В этом слоте нет закреплённого активного навыка.",
		"MSG_ABILITY_FORM_LOCKED": "Текущая форма ещё не может использовать этот навык.",
		"MSG_ABILITY_COOLDOWN": "Навык «%s» восстанавливается: осталось ходов — %d.",
		"MSG_ABILITY_CANCELLED": "Выбор цели отменён.",
		"MSG_DASH_NO_TARGET": "Для рывка нет свободного исследованного пути.",
		"MSG_DASH_TARGETING": "Рывок: выберите подсвеченную клетку. Два направления одновременно — диагональ; Enter — подтвердить, Esc — отменить.",
		"MSG_DASH_INVALID": "В эту клетку нельзя совершить рывок.",
		"MSG_DASH_INVALID_HIDDEN": "Рывок нельзя направить в скрытую клетку.",
		"MSG_DASH_INVALID_TILE": "Эта клетка непроходима для рывка.",
		"MSG_DASH_INVALID_OCCUPIED": "Путь рывка преграждает существо.",
		"MSG_DASH_INVALID_PATH": "Путь рывка преграждает стена или закрытая дверь.",
		"MSG_DASH_COMPLETE": "Рывок завершён: пройдено клеток — %d.",
		"MSG_DASH_CHEST": " Сундук подобран только в конечной клетке рывка.",
		"MSG_ENEMY_DASH": " %s совершает рывок и останавливается рядом.",
		"MSG_DOUBLE_ATTACK_SECOND": " Второй удар: %s",
		"MSG_PASSIVE_DOUBLE_STRIKE": " Повторный удар: %s",
		"MSG_CIRCULAR_ATTACK": "Круговая атака поражает всех врагов рядом.",
		"MSG_CIRCULAR_NO_TARGETS": "Для круговой атаки рядом нет целей.",
		"MSG_EXIT_BLOCKED": "Лестница наверх ещё не обнаружена.",
		"MSG_FOOD_GAINED": " Получено еды: %d.",
		"MSG_CAMP_EAT": "Вы устраиваете привал и съедаете 1 еду. Сытость: %d%%.",
		"MSG_CAMP_NO_FOOD": "Для привала с едой нужны мясные припасы.",
		"MSG_CAMP_FULL": "Плоть уже насыщена.", "MSG_CAMP_SKELETON": "Скелету нечего кормить.",
		"MSG_HUNGER_TICK": " Сытость: %d%%.", "MSG_REGENERATED": " Регенерация восстанавливает %d HP.",
		"MSG_STARVATION": " Сытость исчерпана: тело теряет %d HP.",
		"MSG_CRADLE_APPEARED": "На этом уровне обнаружена Колыбель.",
		"MSG_CRADLE_REQUIRED": "Изменить форму можно только внутри Колыбели.",
		"MSG_CRADLE_TILE": "Перед вами Колыбель. Здесь можно оплатить следующую стадию формы.",
		"MSG_CRADLE_USED": "Эта Колыбель уже преобразила тело и теперь молчит.",
		"MSG_CRADLE_MAX": "Колыбель не может улучшить предельную форму.",
		"MSG_CRADLE_NEEDS_SOULS": "Для следующей стадии Колыбели нужно переносимых душ: %d.",
		"MSG_CRADLE_NEEDS_SOUL_LEVEL": "Нужен уровень души %d. Текущий уровень души: %d.",
		"MSG_CRADLE_EVOLVED": "Колыбель перестраивает тело в форму «%s», поглощая %d душ.",
		"CRADLE_CONFIRM_TITLE": "Подтвердите эволюцию",
		"CRADLE_CONFIRM_DESC": "%s → %s\nСтоимость: %d переносимых душ · с собой: %d\nУровень души: нужен %d · текущий %d",
		"CRADLE_CONFIRM_BUTTON": "Эволюционировать — %d душ",
		"CRADLE_CONFIRM_CANCEL": "Остаться в текущей форме",
		"CRADLE_CONFIRM_UNAVAILABLE": "Эволюция недоступна",
		"CRADLE_CONFIRM_LEVEL_BLOCKED": "Нужен уровень души %d",
		"BOSS_WARNING_TITLE": "Подняться выше?",
		"BOSS_WARNING_DESC": "Вы ощущаете сильную душу за лестницей.\nПродолжить восхождение на %d-й уровень?",
		"BOSS_WARNING_CONFIRM": "Подняться на %d-й уровень",
		"BOSS_WARNING_CANCEL": "Остаться и подготовиться",
		"SIDEBAR_HUNGER": "Сытость: %d%%", "SIDEBAR_FOOD": "Еда: %d",
		"CHARACTER_SURVIVAL": "Сытость: %d%% · Еда: %d",
		"SKILLS_TITLE": "НАВЫКИ", "SKILL_TAB_SKELETON": "Скелет", "SKILL_TAB_ZOMBIE": "Зомби",
		"SKILL_TAB_GHOUL": "Гуль", "SKILL_TAB_REVENANT": "Ревенант",
		"SKILL_TAB_ALMOST_HUMAN": "Почти человек",
		"SKILL_TAB_LOCKED": "%s 🔒", "SKILL_LEVEL": "Ур. %d/%d", "SKILL_COST": "Цена: %d душ",
		"SKILL_KIND_ACTIVE": "АКТИВНЫЙ · квадрат", "SKILL_KIND_PASSIVE": "ПАССИВНЫЙ · круг",
		"SKILL_MAX": "Максимальный уровень",
		"SKILL_BRANCH_BODY_BONES": "Тело — Кости", "SKILL_BRANCH_BODY_FLESH": "Тело — Плоть",
		"SKILL_BRANCH_BODY_GUT": "Тело — Чрево", "SKILL_BRANCH_BODY_CNS": "Тело — ЦНС",
		"SKILL_BRANCH_BODY_APPEARANCE": "Тело — Облик", "SKILL_BRANCH_MAGIC": "Магия",
		"SKILL_BRANCH_MANEUVER": "Манёвр",
		"SKILL_BRANCH_COMBAT": "Бой", "SKILL_BRANCH_BODY": "Тело",
		"SKILL_BRANCH_SENSES": "Чувства", "SKILL_BRANCH_BASIC_ATTACK": "Базовая атака",
		"SKILL_BRANCH_ABILITY": "Способность", "SKILL_BRANCH_APPEARANCE": "Облик",
		"SKILL_DETAIL_TYPE_ACTIVE": "Тип: активный", "SKILL_DETAIL_TYPE_PASSIVE": "Тип: пассивный",
		"SKILL_DETAIL_DESCRIPTION": "Описание: %s", "SKILL_DETAIL_EFFECT": "Эффект: %s",
		"SKILL_DETAIL_MANA": "Мана: %d", "SKILL_DETAIL_COOLDOWN": "Откат: %d ходов",
		"SKILL_DETAIL_REQUIREMENT": "Требование: %s", "SKILL_DETAIL_NOT_APPLICABLE": "нет",
		"SKILL_DETAIL_STAGE": "стадия «%s»", "SKILL_DETAIL_REQUIRES": "навык %s",
		"SKILL_STATUS_LEARN_AVAILABLE": "Навык доступен для изучения.",
		"SKILL_STATUS_UPGRADE_AVAILABLE": "Доступно повышение уровня навыка.",
		"SKILL_STATE_LOCKED": "Закрыто", "SKILL_STATE_AVAILABLE": "Доступно",
		"SKILL_STATE_LEARNED": "Изучено", "SKILL_STATE_MAX": "MAX",
		"SKILL_ACTION_LEARN": "Изучить — %d душ", "SKILL_ACTION_UPGRADE": "Улучшить — %d душ",
		"SKILL_ACTION_MAX": "Максимальный уровень", "SKILL_ACTION_UNAVAILABLE": "Недоступно",
		"SKILL_STRONG_BONES": "Крепкие кости", "SKILL_STRONG_BONES_DESC": "+3 максимального HP за уровень",
		"SKILL_FLEXIBLE_JOINTS": "Гибкие суставы", "SKILL_FLEXIBLE_JOINTS_DESC": "+2 к эффективной Ловкости",
		"SKILL_STRONG_SPINE": "Крепкий позвоночник", "SKILL_STRONG_SPINE_DESC": "+1 к эффективной Живучести",
		"SKILL_FUNDAMENTALS": "Развитие основ", "SKILL_FUNDAMENTALS_DESC": "+5 свободных очков характеристик",
		"SKILL_MAGIC_AWAKENING": "Пробуждение магии", "SKILL_MAGIC_AWAKENING_DESC": "+5 маны и доступ к магической ветке",
		"SKILL_MAGIC_MISSILE": "Магическая стрела", "SKILL_MAGIC_MISSILE_DESC": "10 маны · урон 3 +1/ур. · дальность 3",
		"SKILL_MAGIC_MISSILE_RANGE": "Дальняя стрела", "SKILL_MAGIC_MISSILE_RANGE_DESC": "+2 клетки дальности Магической стрелы",
		"SKILL_MAGIC_RICOCHET": "Рикошет", "SKILL_MAGIC_RICOCHET_DESC": "20% +5%/ур. · прыжок к врагу в радиусе 4",
		"SKILL_FLESH_REGENERATION": "Кровеносная система", "SKILL_FLESH_REGENERATION_DESC": "Активирует лечение по параметру регенерации",
		"SKILL_MUSCLE_FIBERS": "Мышечные волокна", "SKILL_MUSCLE_FIBERS_DESC": "+1 к эффективной Силе за уровень",
		"SKILL_STOMACH": "Желудок", "SKILL_STOMACH_DESC": "Открывает сытость и лагерный статус «Сытость»",
		"SKILL_EARS": "Уши", "SKILL_EARS_DESC": "Открывает слух и обезличенные отметки скрытого шума",
		"SKILL_SHARP_VISION": "Острое зрение", "SKILL_SHARP_VISION_DESC": "+1 клетка обзора",
		"SKILL_NERVOUS_SYSTEM": "Нервная система", "SKILL_NERVOUS_SYSTEM_DESC": "Открывает лагерный статус «Отдых»",
		"SKILL_DASH": "Рывок", "SKILL_DASH_DESC": "До 3 клеток в любом направлении по свободной линии",
		"SKILL_DOUBLE_ATTACK": "Двойная атака", "SKILL_DOUBLE_ATTACK_DESC": "Два независимых удара по одной цели за ход",
		"SKILL_ALMOST_DOUBLE_STRIKE": "Повторный удар", "SKILL_ALMOST_DOUBLE_STRIKE_DESC": "10% +2 п.п./ур. повторить обычную атаку",
		"SKILL_CIRCULAR_ATTACK": "Круговая атака", "SKILL_CIRCULAR_ATTACK_DESC": "Отдельный удар по всем 8 соседним клеткам",
		"SKILL_CHOOSE_APPEARANCE": "Выбор облика", "SKILL_CHOOSE_APPEARANCE_DESC": "Позволяет выбрать облик любой открытой формы",
		"SKILL_STRONG_BONES_DETAIL": "Укрепляет костяную основу тела и повышает его живучесть.",
		"SKILL_FLEXIBLE_JOINTS_DETAIL": "Гибкие суставы настоящего тела добавляют 2 к Ловкости без изменения базового значения.",
		"SKILL_STRONG_SPINE_DETAIL": "Крепкий позвоночник настоящего тела добавляет 1 к Живучести без изменения базового значения.",
		"SKILL_FUNDAMENTALS_DETAIL": "Развитие основ почти человеческого тела один раз выдаёт 5 свободных очков характеристик.",
		"SKILL_MAGIC_AWAKENING_DETAIL": "Пробуждает запас маны и открывает путь к скелетной магии.",
		"SKILL_MAGIC_MISSILE_DETAIL": "Позволяет выпустить направленный магический снаряд по видимой цели.",
		"SKILL_MAGIC_MISSILE_RANGE_DETAIL": "Учит удерживать магический снаряд стабильным на большей дистанции.",
		"SKILL_MAGIC_RICOCHET_DETAIL": "Даёт магическому снаряду шанс перескочить на вторую цель.",
		"SKILL_FLESH_REGENERATION_DETAIL": "Развитая кровеносная система открывает естественное восстановление настоящей формы гуля и выше. Если сытость открыта, лечение работает только при её значении выше нуля.",
		"SKILL_MUSCLE_FIBERS_DETAIL": "Каждый уровень мышечных волокон добавляет 1 к Силе настоящей формы зомби и выше без изменения базового значения.",
		"SKILL_STOMACH_DETAIL": "Развитый желудок открывает механику сытости и получение статуса «Сытость» после настоящего возвращения в лагерь.",
		"SKILL_EARS_DETAIL": "Развитый слух позволяет настоящей форме гуля и выше замечать близкое скрытое движение и запоминать точку атаки из темноты знаком «?». Косметический облик механику не открывает.",
		"SKILL_DASH_DETAIL": "Резко переносит гуля по свободной видимой линии без промежуточной остановки.",
		"SKILL_DOUBLE_ATTACK_DETAIL": "Проводит два независимых обычных удара по одной соседней цели.",
		"SKILL_SHARP_VISION_DETAIL": "Развивает зрение настоящей формы зомби и выше и расширяет видимую область на одну клетку.",
		"SKILL_NERVOUS_SYSTEM_DETAIL": "Изученная Нервная система позволяет настоящей форме ревенанта и выше подготовить лагерный статус «Отдых» при безопасном возвращении. Косметический облик права не даёт.",
		"SKILL_ALMOST_DOUBLE_STRIKE_DETAIL": "Даёт обычной атаке шанс немедленно повториться по выжившей цели.",
		"SKILL_CIRCULAR_ATTACK_DETAIL": "Одновременно атакует каждого врага в восьми соседних клетках.",
		"SKILL_CHOOSE_APPEARANCE_DETAIL": "Позволяет без затрат хода менять внешний облик на любую открытую форму.",
		"STATUS_RESTED": "Отдых",
		"STATUS_RESTED_DESC": "+5 временного HP · +1 физический урон · ускорение Рывка и Двойной атаки",
		"STATUS_SATIATED": "Сытость",
		"STATUS_SATIATED_DESC": "+3 временных HP · +1 к регенерации HP · сытость не снижается",
		"STATUS_TURNS": "осталось ходов: %d", "STATUS_MORE": "Ещё состояний: %d",
		"SKILL_SOULS": "Доступно душ: %d", "SKILL_FREE_STATS": "Свободные статы: %d",
		"ABILITY_BASIC_ATTACK": "Базовая атака", "ABILITY_BASIC_SHOT": "Выстрел",
		"ABILITY_MAGIC_MISSILE": "Магическая стрела",
		"ABILITY_DASH": "Рывок", "ABILITY_DOUBLE_ATTACK": "Двойная атака",
		"ABILITY_CIRCULAR_ATTACK": "Круговая атака", "ABILITY_EMPTY": "Пусто",
		"ABILITY_CHOOSE_APPEARANCE": "Выбор облика",
		"ABILITY_SLOT_ATTACK": "Основная атака", "ABILITY_SLOT_ACTIVE_1": "Активный 1",
		"ABILITY_SLOT_ACTIVE_2": "Активный 2", "ABILITY_SLOT_ACTIVE_3": "Активный 3",
		"ABILITY_ASSIGN_HINT": "Нажмите, чтобы выбрать следующий изученный совместимый навык.",
		"ABILITY_ASSIGNED": "%s: закреплено «%s».",
		"ABILITY_HOTBAR_TOOLTIP": "%s · %s",
		"ABILITY_HOTBAR_COOLDOWN": "%s · %s · восстановление: %d ходов",
		"ABILITY_ATTACK_FALLBACK": "%s\n%s: %d",
		"SKILL_BASE_ONLY": "Распределять свободные характеристики можно только на базе.",
		"SKILL_PURCHASED": "Навык «%s» повышен до уровня %d.",
		"SKILL_NEEDS_SOULS": "Для навыка нужно душ: %d.",
		"SKILL_NEEDS_PREVIOUS": "Сначала изучите предыдущий навык.",
		"SKILL_STAGE_LOCKED": "Сначала достигните этой стадии тела.",
		"SKILL_ALREADY_MAX": "Навык уже развит полностью.",
		"EVOLUTION_MAX": "Предельная форма достигнута",
		"EVOLUTION_NEXT": "%s · %d душ · уровень души %d",
		"TITLE_FLOOR": "Уровень %d", "TITLE_BASE": "Костяное убежище",
		"TITLE_EXIT": "Уровень 1 — Выход",
		"HINT_DUNGEON": "WASD — ход  |  F — основная атака  |  Q — активный 1  |  T — ждать  |  G — лестница",
		"HINT_BASE": "Сохранённые души не теряются. Форма и снаряжение сохраняются до смерти.",
		"HINT_END": "Конец вертикального среза", "SIDEBAR_FORM": "Форма: %s",
		"SIDEBAR_HP": "Здоровье: %d/%d", "SIDEBAR_CARRIED": "Свободные души: %d",
		"SIDEBAR_BANKED": "Души на базе: %d", "SIDEBAR_EVOLUTION": "Эволюция: %s",
		"SIDEBAR_SOULS_COMBINED": "Души: с собой %d · на базе %d",
		"SOUL_COUNTER": "Души: %d (%d)", "DUNGEON_SOUL_COUNTER": "%d (%d)",
		"SOUL_LEVEL_LABEL": "Уровень души: %d",
		"SOUL_LEVEL_APPEARANCE_LABEL": "Уровень души: %d\nФорма: %s · Облик: %s",
		"CHARACTER_SOUL_FORM_APPEARANCE": "Уровень души: %d\nФорма: %s\nОблик: %s",
		"APPEARANCE_TITLE": "Выбор облика",
		"APPEARANCE_SUMMARY": "Настоящая форма: %s\nВыбранный облик: %s",
		"APPEARANCE_COSMETIC_HINT": "Только внешний вид. Характеристики, слоты, сытость и способности определяет настоящая форма.",
		"APPEARANCE_CONFIRM": "Применить облик", "APPEARANCE_CANCEL": "Отмена [Esc / B]",
		"MSG_APPEARANCE_CHANGED": "Выбран косметический облик: %s.",
		"SIDEBAR_CRADLE_CHANCE": "Следующий шанс Колыбели: %d%%",
		"SIDEBAR_EQUIPMENT": "Снаряжение:", "UPGRADE_COST": "Укрепить убежище — %d душ",
		"CAMP_RESOURCES": "Материалы: дерево %d · камень %d · ткань %d",
		"BASE_RESOURCE_WOOD_TOOLTIP": "Древесина: %d",
		"BASE_RESOURCE_STONE_TOOLTIP": "Камень: %d",
		"BASE_RESOURCE_CLOTH_TOOLTIP": "Ткань: %d",
		"BASE_SOULS_TOOLTIP": "Души с собой: %d · всего: %d",
		"CAMP_MATERIAL_HINT": "Дерево и камень — в сундуках; ткань — из разбора брони.",
		"CAMP_BUILD_CRUSHER": "Построить дробилку — 5 дерева · 5 камня",
		"CAMP_BUILD_WHETSTONE": "Поставить точильный камень — 10 дерева · 10 камня · 5 ткани",
		"CAMP_BUILD_RITUAL_TABLE": "Построить ритуальный стол — 10 дерева · 10 камня · 5 ткани",
		"CAMP_BUILD_CAMPFIRE": "Сложить костёр — 3 дерева · 3 камня · +1 уровень души",
		"CAMP_BUILT_CRUSHER": "Дробилка установлена", "CAMP_BUILT_WHETSTONE": "Точильный камень установлен",
		"CAMP_BUILT_RITUAL_TABLE": "Ритуальный стол установлен",
		"CAMP_BUILT_CAMPFIRE": "Костёр сложен · +1 уровень души",
		"MSG_CAMPFIRE_SOUL_LEVEL": "Костёр укрепляет душу. Уровень души: %d.",
		"MSG_CAMP_UPGRADE_BUILT": "В лагере установлено улучшение: %s.",
		"MSG_CAMP_UPGRADE_NEEDS": "Для постройки не хватает материалов.",
		"MSG_CAMP_UPGRADE_EXISTS": "Это улучшение уже установлено.",
		"CHARACTER_TAB_SKILLS": "Навыки", "CHARACTER_TAB_INVENTORY": "Инвентарь",
		"INVENTORY_SLOT_LOCKED": "закрыто", "INVENTORY_SELECT_ITEM": "Выберите вещь или занятый слот.",
		"INVENTORY_PAGE": "Страница %d / %d", "INVENTORY_EQUIP": "Экипировать",
		"INVENTORY_UNEQUIP": "Снять", "INVENTORY_DISMANTLE": "Разобрать",
		"INVENTORY_DISMANTLE_ALL": "Разобрать всё",
		"INVENTORY_DISMANTLE_ALL_CONFIRM_BUTTON": "Точно всё?",
		"INVENTORY_DISMANTLE_ALL_CONFIRM": "Повторное нажатие разберёт все несвязанные вещи в инвентаре. Экипировка и связанные вещи останутся.",
		"INVENTORY_UPGRADE": "Улучшить оружие", "INVENTORY_UPGRADE_MAX": "Максимальное улучшение +3",
		"INVENTORY_UPGRADE_WEAPON_ONLY": "Улучшать можно только оружие",
		"INVENTORY_UPGRADE_SELECT_SHORT": "Выбрать оружие",
		"INVENTORY_UPGRADE_CHANCE": "Улучшить до +%d · шанс %d%%",
		"INVENTORY_UPGRADE_CHANCE_COST": "До +%d · %d%% · %d камня, %d дерева, %d ткани",
		"INVENTORY_ITEM_DETAIL": "Слот: %s\nУрон: %d · Точность: %d · HP: %d · Мана: %d",
		"INVENTORY_RANGED_ITEM_DETAIL": "Слот: %s\nДальний урон: %d · Точность: %d · Дальность: %d\nHP: %d · Мана: %d",
		"INVENTORY_WEAPON_CLASS": "Класс: %s",
		"INVENTORY_FILTER_ALL": "Все", "INVENTORY_EMPTY_FILTER": "В этой категории нет вещей",
		"INVENTORY_FILTER_WEAPONS": "Оружие", "INVENTORY_FILTER_OFFHAND": "Вторая рука",
		"INVENTORY_FILTER_ARMOR": "Броня", "INVENTORY_FILTER_ACCESSORIES": "Аксессуары",
		"INVENTORY_FILTER_BACKPACK": "Рюкзак",
		"INVENTORY_SELECTION_STALE": "Выбор устарел — выберите вещь ещё раз.",
		"ACTION_PREFIX_OUTGOING": "↑ ИСХ:", "ACTION_PREFIX_INCOMING": "↓ ВХОД:",
		"ACTION_PREFIX_LOOT": "▣ ДОБЫЧА:", "ACTION_PREFIX_NEUTRAL": "· СИСТ:",
		"INVENTORY_SELECTED_PANEL": "ВЫБРАННАЯ ВЕЩЬ", "INVENTORY_EQUIPPED_PANEL": "НАДЕТО В СЛОТЕ",
		"INVENTORY_EMPTY": "Пусто", "INVENTORY_SLOT_LINE": "Слот: %s",
		"INVENTORY_LEVEL": "Улучшение: +%d", "INVENTORY_COUNT": "Количество: ×%d",
		"INVENTORY_SALVAGE": "Разбор: дерево %d · камень %d · ткань %d",
		"INVENTORY_SOUL_BONUS": "Бонус душ",
		"INVENTORY_SOUL_LEVEL_BONUS": "+%d Уровень души",
		"INVENTORY_PERMANENT_LOCKED": "Не хочется снимать",
		"INVENTORY_SOURCE_INVENTORY": "Инвентарь", "INVENTORY_SOURCE_EQUIPPED": "Надето",
		"INVENTORY_SOURCE_LOCKED": "Закрытый слот",
		"INVENTORY_SERVICE_CRUSHER": "ДРОБИЛКА · РАЗБОР ВЕЩЕЙ",
		"INVENTORY_SERVICE_WHETSTONE": "ТОЧИЛЬНЫЙ КАМЕНЬ · ОРУЖИЕ",
		"INVENTORY_SERVICE_RITUAL": "РИТУАЛЬНЫЙ СТОЛ · ПРИВЯЗКА ВЕЩЕЙ",
		"INVENTORY_CLOSE_SERVICE": "Закрыть окно [Esc / B]",
		"INVENTORY_BOUND_STATUS": "Связано с героем · сохраняется после смерти",
		"INVENTORY_BOUND_SHORT": "связано",
		"INVENTORY_BIND_EXPLANATION": "Ритуал связывает один экземпляр вещи с героем. Он не потеряется после смерти.",
		"INVENTORY_BIND_ACTION": "Связать — %d душ",
		"INVENTORY_BIND_ALREADY": "Уже связано",
		"INVENTORY_BIND_TOOLTIP": "Связать один экземпляр вещи с героем за %d душ",
		"INVENTORY_BIND_ALREADY_DESC": "Эта вещь уже сохранится после смерти",
		"INVENTORY_REASON_MAX": "Оружие уже улучшено до +3.",
		"INVENTORY_REASON_RESOURCES": "Не хватает 10 камня, 2 дерева и 1 ткани.",
		"INVENTORY_PREVIOUS_PAGE": "Предыдущая страница", "INVENTORY_NEXT_PAGE": "Следующая страница",
		"CAMP_OBJECT_CRUSHER": "Дробилка\nОткрыть [Enter / A]",
		"CAMP_OBJECT_CRUSHER_TOOLTIP": "Открыть меню разборки вещей",
		"CAMP_OBJECT_WHETSTONE": "Точильный камень\nОткрыть [Enter / A]",
		"CAMP_OBJECT_WHETSTONE_TOOLTIP": "Открыть меню улучшения оружия",
		"CAMP_OBJECT_RITUAL_TABLE": "Ритуальный стол\nОткрыть [Enter / A]",
		"CAMP_OBJECT_RITUAL_TABLE_TOOLTIP": "Открыть меню привязки вещей",
		"CAMP_OBJECT_STORAGE_CHEST": "Сундук хранения\nОткрыть [Enter / A]",
		"CAMP_OBJECT_STORAGE_CHEST_TOOLTIP": "Открыть хранилище предметов",
		"STORAGE_TITLE": "ХРАНИЛИЩЕ",
		"STORAGE_PLAYER_INVENTORY": "Инвентарь игрока",
		"STORAGE_HEADING": "Хранилище",
		"STORAGE_INSTRUCTIONS": "Нажмите стопку, чтобы переместить 1. Выберите стопку и нажмите стрелку, чтобы переместить всё.",
		"STORAGE_CLOSE": "Закрыть [Esc / B]",
		"STORAGE_CLOSE_TOOLTIP": "Закрыть окно хранилища [Esc / B]",
		"STORAGE_FILTER_TOOLTIP": "Показать категорию: %s",
		"STORAGE_INVENTORY_EMPTY": "В инвентаре нет переносимых предметов",
		"STORAGE_EMPTY": "Хранилище пусто",
		"STORAGE_EMPTY_FILTER": "В этой категории нет предметов",
		"STORAGE_MOVE_ALL_RIGHT": "Всё →",
		"STORAGE_MOVE_ALL_LEFT": "← Всё",
		"STORAGE_MOVE_ALL_TO_STORAGE": "Переместить всю выбранную стопку в хранилище",
		"STORAGE_MOVE_ALL_TO_INVENTORY": "Переместить всю выбранную стопку в инвентарь игрока",
		"STORAGE_SELECT_INVENTORY_STACK": "Сначала выберите стопку в инвентаре игрока",
		"STORAGE_SELECT_STORAGE_STACK": "Сначала выберите стопку в хранилище",
		"STORAGE_MOVE_ONE_TOOLTIP": "%s: переместить 1 в «%s»",
		"STORAGE_MOVED_ONE": "%s: перемещён 1 предмет в «%s».",
		"STORAGE_MOVED_COUNT": "Перемещено %d × %s в «%s».",
		"STORAGE_SAVE_FAILED": "Не удалось сохранить игру: перенос отменён.",
		"STORAGE_REASON_UNBUILT": "Сначала постройте сундук хранения.",
		"STORAGE_REASON_MISSING": "Этой стопки больше нет в выбранном списке.",
		"STORAGE_REASON_INSUFFICIENT": "В стопке недостаточно предметов.",
		"STORAGE_REASON_COUNT": "Можно перемещать только положительное целое количество.",
		"STORAGE_REASON_ITEM": "Этот предмет нельзя хранить.",
		"STORAGE_REASON_FAILED": "Не удалось переместить предмет. Содержимое не изменено.",
		"MAGIC_MISSILE_TOOLTIP": "Урон %d · дальность %d · %d маны · попадание 100%% · нужна прямая видимость",
		"MAGIC_LOCKED_TOOLTIP": "Открывается навыком «Магическая стрела»",
		"BASE_CENTER": "КОСТЯНОЕ УБЕЖИЩЕ",
		"STORY_INTRO_1": "Скелет долго бродил по нижним уровням, не помня ни имени, ни цели.",
		"STORY_INTRO_2": "Первой найденной вещью оказалось старое пончо. Почти нелепая, но уже своя одежда.",
		"STORY_INTRO_3": "А затем внутри пустой грудной клетки что-то отозвалось.",
		"STORY_DEATH": "Спустя время останки провалились через люк обратно в тихий закуток.",
		"STORY_CONTINUE": "Нажмите, чтобы продолжить",
		"EXIT_CENTER": "СВЕТ С ПОВЕРХНОСТИ",
		"INSPECT_HEADER_AUTO": "ОСМОТР · АВТО", "INSPECT_HEADER_SELECTED": "ОСМОТР · ВЫБРАНО",
		"INSPECT_NOISE_SOURCE": "Источник шума",
		"INSPECT_NONE": "Поблизости ничего интересного.",
		"INSPECT_TARGET": "%s · %d кл.",
		"INSPECT_ENEMY_STATS": "HP %d/%d · Урон %d · Точность %d · Обзор %d",
		"INSPECT_ITEM_STATS": "Слот: %s · Урон %d · HP %d",
		"INSPECT_CHEST": "Сундук", "INSPECT_CHEST_DESC": "Внутри предмет и, возможно, дерево или камень.",
		"INSPECT_BASE": "Спуск на базу", "INSPECT_EXIT": "Подъём наверх",
		"INSPECT_START": "Точка входа", "INSPECT_WALL": "Каменная стена",
		"INSPECT_BOSS_DOOR": "Запечатанная дверь арены",
		"INSPECT_BOSS_DOOR_OPEN": "Открытая дверь арены",
		"INSPECT_CRADLE": "Колыбель", "INSPECT_CRADLE_READY": "Следующая форма: %s · Цена: %d душ · Уровень души: %d",
		"INSPECT_CRADLE_USED": "Преобразование на этом уровне уже совершено",
		"INSPECT_FLOOR": "Каменный пол", "INSPECT_VOID": "Непроходимая пустота",
	},
	"en": {
		"INSPECT_ARACHNID_ABILITY": "Double attack: 2 strikes, cooldown 15.",
		"INSPECT_BONE_CROSSBOWMAN_ABILITY": "Shot: prepare 2, idle 1, cooldown 3.",
		"INSPECT_SLAG_SMITH_ABILITY": "Wind-up 1: damage 5 at marked cell, cooldown 6.",
		"INVENTORY_BACKPACK_REMOVAL": "First removal: up to −200 turns of both effects.",
		"INVENTORY_LAMP_HEARING": "Does not unlock Ears.",
		"MSG_ENEMY_PREPARING": "%s prepares a strong attack. Turns remaining: %d.",
		"INSPECT_PREPARATION": "Preparation, turns remaining: %d",
		"INSPECT_CRYPT": "Crypt",
		"BIOME_WEAVING_CRYPTS": "Weaver Catacombs",
		"PARAM_PREPARATION": "Satiated/Rested turns",
		"INVENTORY_MARK_KEEP": "Keep",
		"INVENTORY_MARK_SALVAGE": "Salvage",
		"INVENTORY_MARKED_ONLY": "Marked salvage only",
		"INVENTORY_KEEP_CONFIRM": "Keep: confirm salvaging one item.",
		"INVENTORY_KEEP_CONFIRM_BUTTON": "Confirm",
		"CAMP_KETTLE": "Expedition Kettle",
		"CAMP_BUNK": "Cloth Bunk",
		"CAMP_MURAL": "Mural",
		"CAMP_WORKBENCH": "Workbench",
		"CAMP_WRITING_SET": "Writing Set",
		"CAMP_TEXTILE_AREA": "Textile Area",
		"CAMP_ROCKING_CHAIR": "Rocking Chair",
		"CAMP_RECORD_PLAYER": "Record Player",
		"CAMP_STORAGE_CHEST": "Storage Chest",
		"CAMP_BUILD_KETTLE": "Kettle: wood 6, stone 8, cloth 2",
		"CAMP_BUILD_BUNK": "Bunk: wood 8, cloth 6",
		"CAMP_BUILD_MURAL": "Mural: 12 / 20 / 5, souls 60, tail 1",
		"CAMP_BUILD_WORKBENCH": "Workbench: Free",
		"CAMP_BUILD_WRITING_SET": "Writing Set: Free",
		"CAMP_BUILD_TEXTILE_AREA": "Textile Area: Free",
		"CAMP_BUILD_ROCKING_CHAIR": "Rocking Chair: wood 30",
		"CAMP_BUILD_RECORD_PLAYER": "Record Player: Free",
		"CAMP_BUILD_STORAGE_CHEST": "Storage Chest: wood 20, stone 4, cloth 3",
		"CAMP_BUILT_KETTLE": "Expedition Kettle built",
		"CAMP_BUILT_BUNK": "Cloth Bunk built",
		"CAMP_BUILT_MURAL": "Mural — victory over the Minotaur",
		"CAMP_BUILT_WORKBENCH": "Workbench built",
		"CAMP_BUILT_WRITING_SET": "Writing Set ready",
		"CAMP_BUILT_TEXTILE_AREA": "Textile Area ready",
		"CAMP_BUILT_ROCKING_CHAIR": "Rocking Chair built",
		"CAMP_BUILT_RECORD_PLAYER": "Record Player installed",
		"CAMP_BUILT_STORAGE_CHEST": "Storage Chest built",
		"CAMP_KETTLE_DESC": "On departure, spend 1 food for +100 turns of Satiated.",
		"CAMP_BUNK_DESC": "Prepared departure: +100 turns of Rested.",
		"CAMP_CAMPFIRE_DESC": "Permanently +1 Soul Level; unlocks the Expedition Kettle.",
		"CAMP_CRUSHER_DESC": "Unlocks salvaging unbound items into materials.",
		"CAMP_WHETSTONE_DESC": "Unlocks resource-paid weapon upgrades up to +3.",
		"CAMP_RITUAL_TABLE_DESC": "Unlocks binding one item instance for 25 available souls.",
		"CAMP_MURAL_DESC": "Victory graffiti. Wood 12, stone 20, cloth 5, banked souls 60, Minotaur Tail 1. Permanently +1 Soul Level.",
		"CAMP_WORKBENCH_DESC": "A free work table. Unlocks the Writing Set; provides no separate service.",
		"CAMP_WRITING_SET_DESC": "Old ink and paper. Requires the Workbench; provides no separate service.",
		"CAMP_TEXTILE_AREA_DESC": "A place to mend cloth. Free; provides no separate service.",
		"CAMP_ROCKING_CHAIR_DESC": "The skeleton made this chair for himself. It strengthens his identity and soul like the Mural: permanently +1 Soul Level.",
		"CAMP_RECORD_PLAYER_DESC": "An old mechanical record player. Free; provides no separate service.",
		"CAMP_STORAGE_CHEST_DESC": "Stores movable items between expeditions. Its contents are not lost on death.",
		"CAMP_BUILD_BUTTON": "Build",
		"CAMP_BUILD_TITLE": "BUILD",
		"CAMP_BUILD_CLOSE": "Close [Esc / B]",
		"CAMP_BUILD_FREE": "Free",
		"CAMP_BUILD_STATUS_BUILT": "Built",
		"CAMP_BUILD_STATUS_REQUIRES": "Requires: %s",
		"CAMP_BUILD_STATUS_HIDDEN": "Hidden",
		"CAMP_BUILD_STATUS_AVAILABLE": "Available",
		"CAMP_BUILD_STATUS_INSUFFICIENT": "Insufficient resources",
		"CAMP_BUILD_ACTION": "Build",
		"CAMP_BUILD_PRICE": "Price: %s",
		"CAMP_BUILD_PREREQUISITE": "Build this first: %s.",
		"RESOURCE_WOOD": "Wood",
		"RESOURCE_STONE": "Stone",
		"RESOURCE_CLOTH": "Cloth",
		"RESOURCE_BANKED_SOULS": "Banked souls",
		"RESOURCE_MINOTAUR_TAIL": "Minotaur Tail",
		"CAMP_KETTLE_SELECT": "Prepare kettle: 1 food, +100 Satiated",
		"CAMP_KETTLE_NEEDS_FOOD": "The selected preparation requires 1 food.",
		"CAMP_PREPARATION_DESC": "Returning restores HP and satiety. Timed effects start on departure. Backpack adds 200 turns; first removal subtracts that bonus.",
		"CAMP_START_TOOLTIP": "Begin an expedition. Returning restores HP and satiety; timed effects start on departure.",
		"MSG_MINOTAUR_TAIL": " Received a Minotaur Tail — a permanent trophy for the Mural.",
		"TROPHY_MINOTAUR_TAIL": "Minotaur Tail",
		"ITEM_RUSTY_SABRE": "Rusty Sabre",
		"ITEM_SHORT_CROSSBOW": "Short Crossbow",
		"ITEM_BONE_BUCKLER": "Bone Buckler",
		"ITEM_GRAVEDIGGERS_LAMP": "Gravedigger’s Lamp",
		"ITEM_WATCHMANS_CAP": "Watchman’s Cap",
		"ITEM_ARCHIVISTS_MASK": "Archivist’s Mask",
		"ITEM_WANDERERS_GAMBESON": "Wanderer’s Gambeson",
		"ITEM_LAMELLAR_VEST": "Lamellar Vest",
		"ITEM_SCOUTS_TROUSERS": "Scout’s Trousers",
		"ITEM_HEAVY_LEG_WRAPS": "Heavy Leg Wraps",
		"ITEM_PILGRIMS_BOOTS": "Pilgrim’s Boots",
		"ITEM_AIMING_RING": "Aiming Ring",
		"ITEM_THICKBLOOD_RING": "Thickblood Ring",
		"ITEM_EXPEDITION_BACKPACK": "Expedition Backpack",
		"ENEMY_BLIND_SCAVENGER": "Blind Scavenger",
		"ENEMY_ARACHNID": "Crypt Arachnid",
		"ENEMY_BONE_CROSSBOWMAN": "Bone Crossbowman",
		"ENEMY_SLAG_SMITH": "Slag Smith",
		"GLYPH_BLIND_SCAVENGER": "S",
		"GLYPH_ARACHNID": "A",
		"GLYPH_BONE_CROSSBOWMAN": "C",
		"GLYPH_SLAG_SMITH": "F",
		"ATTR_STRENGTH": "Strength", "ATTR_AGILITY": "Agility", "ATTR_PERCEPTION": "Perception",
		"ATTR_VITALITY": "Vitality", "ATTR_WISDOM": "Wisdom",
		"FORM_SKELETON": "Skeleton", "FORM_ZOMBIE": "Zombie", "FORM_GHOUL": "Ghoul",
		"FORM_REVENANT": "Revenant", "FORM_ALMOST_HUMAN": "Almost Human",
		"TRAIT_SKELETON": "Immune to poison, fragile in melee",
		"TRAIT_ZOMBIE": "More health, but the body is still sluggish",
		"TRAIT_GHOUL": "Powerful attacks and access to equipment for the hands",
		"TRAIT_REVENANT": "Controls relics and holds more soul power",
		"TRAIT_ALMOST_HUMAN": "Can use a full set of human equipment",
		"SLOT_WEAPON": "Weapon", "SLOT_CHARM": "Charm", "SLOT_ARMOR": "Armor",
		"SLOT_HANDS": "Hands", "SLOT_RELIC": "Relic", "SLOT_OFFHAND": "Off hand",
		"SLOT_RIGHT_HAND": "Main Hand", "SLOT_LEFT_HAND": "Off Hand",
		"SLOT_FEET": "Footwear", "SLOT_BODY": "Body", "SLOT_LEGS": "Legs",
		"SLOT_HEAD": "Helmet", "SLOT_TALISMAN": "Talisman", "SLOT_RING_1": "Ring 1",
		"SLOT_RING_2": "Ring 2", "SLOT_BACK": "Backpack", "SLOT_JACKET": "Cloak",
		"CATEGORY_WEAPON": "Weapons", "CATEGORY_OFFHAND": "Off Hand",
		"CATEGORY_FEET": "Footwear", "CATEGORY_BODY": "Body", "CATEGORY_LEGS": "Legs",
		"CATEGORY_HANDS": "Hands", "CATEGORY_HEAD": "Helmets", "CATEGORY_TALISMAN": "Talismans",
		"CATEGORY_RING": "Rings", "CATEGORY_BACK": "Backpack",
		"ITEM_BONE_KNIFE": "Bone Knife", "ITEM_GRAVE_MACE": "Grave Mace",
		"ITEM_BONE_BOW": "Bone Bow",
		"ITEM_OLD_CLAYMORE": "Old Claymore",
		"ITEM_OLD_CLAYMORE_DESC": "A worn, long two-handed sword.",
		"ITEM_SOUL_LOCKET": "Soulcatcher Locket", "ITEM_ROTTING_MAIL": "Stitched Carapace",
		"ITEM_LEATHER_GLOVES": "Leather Gloves", "ITEM_HOLLOW_LANTERN": "Hollow Lantern",
		"ITEM_PILGRIM_SHIELD": "Pilgrim Shield",
		"ITEM_UNEXPECTEDLY_COMFORTABLE_JACKET": "Cozy Jacket",
		"ITEM_UNEXPECTEDLY_COMFORTABLE_JACKET_DESC": "+1 Soul Level",
		"CAMP_CRUSHER": "Crusher", "CAMP_WHETSTONE": "Whetstone",
		"CAMP_RITUAL_TABLE": "Ritual Table", "CAMP_CAMPFIRE": "Campfire",
		"MSG_TWO_HANDED_OFFHAND_BLOCKED": "A two-handed weapon occupies both hands. The Off Hand is unavailable.",
		"WEAPON_CLASS_ONE_HANDED": "One-handed",
		"WEAPON_CLASS_TWO_HANDED": "Two-handed",
		"WEAPON_CLASS_RANGED_TWO_HANDED": "Ranged two-handed",
		"WEAPON_GHOST_TOOLTIP": "This hand is occupied by the two-handed weapon in Main Hand. Selection redirects to Main Hand.",
		"ENEMY_GRAVE_RAT": "Grave Rat", "ENEMY_HOLLOW_GUARD": "Hollow Guard",
		"ENEMY_SOUL_LEECH": "Soul Leech", "ENEMY_SKELETAL_ARCHER": "Skeletal Archer",
		"ENEMY_MINOTAUR": "Minotaur",
		"GLYPH_GRAVE_RAT": "r", "GLYPH_HOLLOW_GUARD": "g", "GLYPH_SOUL_LEECH": "l",
		"GLYPH_SKELETAL_ARCHER": "a", "GLYPH_MINOTAUR": "M", "GLYPH_PLAYER": "P",
		"GLYPH_FORM_SKELETON": "S", "GLYPH_FORM_ZOMBIE": "Z", "GLYPH_FORM_GHOUL": "G",
		"GLYPH_FORM_REVENANT": "R", "GLYPH_FORM_ALMOST_HUMAN": "H",
		"GLYPH_START": "S", "GLYPH_BASE": "B",
		"GLYPH_CHEST": "▣",
		"BTN_START": "Begin Expedition", "BTN_CHARACTER_ACTION": "Char. [E]",
		"BTN_INTERACT": "Action", "BTN_ASCEND": "Up [G]",
		"BTN_WAIT_ONE": "1 turn [T]", "BTN_WAIT_MANY": "%d turns [T]",
		"WAIT_CYCLE_HINT": "Cycle waiting: 1 → 10 → 100 turns",
		"BTN_AUTO_EXPLORE": "Auto [X]", "BTN_AUTO_EXPLORE_STOP": "Stop [X]",
		"BTN_ATTACK": "Attack [F]", "BTN_MAGIC": "Magic [Q]", "BTN_MAGIC_READY": "Missile [Q]",
		"BTN_CAMP": "Camp [R]",
		"BTN_UPGRADE": "Reinforce the Bone Shelter", "BTN_CHARACTER": "Character [E]",
		"BTN_CONTINUE": "Continue", "BTN_FINISH_CREATION": "Finish Creation",
		"BTN_BACK": "Return [Esc]", "BTN_LANGUAGE": "Language: %s", "BTN_MENU": "Menu",
		"BTN_MAIN_MENU": "Main Menu",
		"BTN_NEW_GAME": "Start New Game", "BTN_NEW_GAME_CONFIRM": "Really start over?",
		"BTN_EXIT": "Exit Game", "BTN_EXIT_CONFIRM": "Really exit?",
		"SAVE_MENU_TITLE": "ALMSTH", "SAVE_MENU_SUBTITLE": "Choose whose story to continue.",
		"STAGE1C_BUILD_STATUS": "Stage 1C · Local build",
		"SAVE_MENU_LOAD_SUBTITLE": "Saved characters — newest entries first",
		"SAVE_MENU_EMPTY_SUBTITLE": "No saves yet: create a new character.",
		"SAVE_MENU_CONTINUE": "Continue Latest", "SAVE_MENU_RESUME": "Continue",
		"SAVE_MENU_NEW": "New Character",
		"SAVE_MENU_LOAD": "Load Save", "SAVE_MENU_BACK": "Back [Esc / B]",
		"SAVE_MENU_SETTINGS": "Settings", "SAVE_MENU_EXIT": "Exit Game",
		"SAVE_MENU_EMPTY": "There are no saves yet.", "SAVE_MENU_UNKNOWN_DATE": "unknown date",
		"SAVE_MENU_ROW": "%s  ·  %s  ·  total souls: %d",
		"SAVE_MENU_ROW_META": "%s  ·  total souls: %d",
		"SAVE_MENU_INCOMPATIBLE_NAME": "Incompatible save",
		"SAVE_MENU_INCOMPATIBLE_META": "Version %d · loading unavailable",
		"SAVE_MENU_INCOMPATIBLE_TOOLTIP": "%s · version %d is incompatible. This save can only be deleted.",
		"SAVE_MENU_CORRUPT_NAME": "Corrupt save",
		"SAVE_MENU_CORRUPT_META": "Corrupt family · loading unavailable",
		"SAVE_MENU_CORRUPT_TOOLTIP": "%s · the family is corrupt (error %d). It was not changed automatically; keep the game open and report the code if you need help.",
		"SAVE_MENU_DELETE_TOOLTIP": "Delete save: %s",
		"SAVE_MENU_DELETE_TITLE": "Delete save?",
		"SAVE_MENU_DELETE_BODY": "Character: %s\nSaved: %s\n\nThis action cannot be undone.",
		"SAVE_MENU_DELETE_ACTIVE_WARNING": "The current game remains in memory. After Continue, a new save will be created separately.",
		"SAVE_MENU_DELETE_NO": "No, keep it",
		"SAVE_MENU_DELETE_YES": "Yes, delete",
		"SAVE_MENU_DELETE_ERROR": "The save could not be deleted (error %d). Check the list and try again.",
		"SAVE_MENU_PREVIOUS": "← Previous", "SAVE_MENU_NEXT": "Next →", "SAVE_MENU_PAGE": "Page %d / %d",
		"SAVE_POLICY_OVERWRITE": "Overwrite one slot for this character",
		"SAVE_POLICY_HINT": "Turn off to keep separate snapshots of meaningful returns.",
		"MSG_SAVE_FAILED": "The game could not be saved (error %d).",
		"MSG_LOAD_FAILED": "The selected save could not be loaded.",
		"MSG_SAVE_OCCUPIED_INCOMPATIBLE": "The game could not be saved because the selected occupied family is incompatible with safe overwrite (error %d). The family was not changed, and the current game remains in memory. Keep the game open; select a known-good save or report this error code.",
		"MSG_SAVE_CORRUPT_FAMILY": "The game could not be saved because the selected save family is corrupt or incompatible (error %d). The family was not changed, and the current game remains in memory. Keep the game open; select only a known-good save or report this error code.",
		"MSG_SAVE_INVALID_LIVE_SNAPSHOT": "The game could not be saved because the current state failed strict validation (error %d). Save files were not changed, and the game remains in memory. Keep the game open and report this error code.",
		"MSG_SAVE_WRITE_VERIFICATION_FAILED": "The game could not be saved because the temporary write failed verification (error %d). The save family was not changed, and the current game remains in memory. Keep the game open and report this error code.",
		"MSG_LOAD_CORRUPT_FAMILY": "The corrupt save family could not be loaded (error %d). Its files were not changed, and the current session stayed unchanged. Select a known-good save or report this error code.",
		"SETTINGS_TITLE": "Settings",
		"BTN_SETTINGS_CLOSE": "Return [Esc]", "SETTINGS_WINDOWED": "Mode: Windowed",
		"SETTINGS_FULLSCREEN": "Mode: Fullscreen",
		"SETTINGS_INPUT_SUMMARY": "Keyboard and gamepad bindings can be changed.",
		"SETTINGS_SOUND_ON": "Sound: On", "SETTINGS_SOUND_OFF": "Sound: Off",
		"SETTINGS_BACKGROUND_VOLUME": "Background: %d%%", "SETTINGS_ACTIONS_VOLUME": "Actions: %d%%",
		"SETTINGS_ZOOM": "Zoom: %s · %d px", "SETTINGS_ZOOM_MAP": "Map",
		"SETTINGS_ZOOM_TACTICS": "Tactics", "SETTINGS_ZOOM_DETAILS": "Details",
		"SETTINGS_ZOOM_DESC": "Changes only cell and camera size; dungeon rules stay unchanged. In the dungeon: + zoom in, − zoom out.",
		"SETTINGS_AUTO_SPEED": "Automatic movement speed: %s",
		"SETTINGS_AUTO_SPEED_NORMAL": "Normal", "SETTINGS_AUTO_SPEED_FASTER": "Faster",
		"SETTINGS_AUTO_SPEED_VERY_FAST": "Very fast", "SETTINGS_AUTO_SPEED_MAXIMUM": "Maximum",
		"SETTINGS_AUTO_SPEED_DESC": "Speeds up auto-explore and the route to stairs. Does not change turn cost or manual movement speed.",
		"BTN_CONTROLS": "Configure Controls",
		"CONTROLS_TITLE": "Controls",
		"CONTROLS_SUBTITLE": "Select a binding, then press a new key or gamepad control.",
		"CONTROLS_ACTION_HEADER": "Action", "CONTROLS_KEYBOARD_HEADER": "Keyboard",
		"CONTROLS_GAMEPAD_HEADER": "Gamepad", "CONTROLS_BACK": "Return [Esc / B]",
		"CONTROLS_RESET": "Reset to Defaults", "CONTROLS_RESET_CONFIRM": "Confirm Reset",
		"CONTROLS_RESET_WARNING": "Press again to restore every default binding. Esc / B cancels.",
		"CONTROLS_RESET_DONE": "Default bindings restored.",
		"CONTROLS_NOT_ASSIGNED": "Not assigned",
		"CONTROLS_WAIT_KEYBOARD": "Waiting for a key… Esc cancels.",
		"CONTROLS_WAIT_GAMEPAD": "Waiting for a gamepad button or direction… B cancels.",
		"CONTROLS_WRONG_DEVICE": "Waiting for input from: %s.",
		"CONTROLS_CONFLICT": "%s is already assigned to: %s. Enter / A moves it here · Esc / B cancels.",
		"CONTROLS_CONFLICT_CONFIRM": "Move Binding Here",
		"CONTROLS_CONFLICT_CANCEL": "Keep Existing Binding",
		"CONTROLS_APPLIED": "%s assigned to “%s”.",
		"CONTROLS_CANCELLED": "Change cancelled.",
		"CONTROLS_NAV_HINT": "Arrows / D-pad — select · Enter / A — change · Esc / B — back",
		"INPUT_ACTION_MOVE_UP": "Move Up", "INPUT_ACTION_MOVE_DOWN": "Move Down",
		"INPUT_ACTION_MOVE_LEFT": "Move Left", "INPUT_ACTION_MOVE_RIGHT": "Move Right",
		"INPUT_ACTION_ATTACK": "Primary Attack", "INPUT_ACTION_CAST_SPELL": "Active Slot 1",
		"INPUT_ACTION_WAIT": "Wait a Turn", "INPUT_ACTION_AUTO_EXPLORE": "Explore Floor",
		"INPUT_ACTION_CAMP": "Camp",
		"INPUT_ACTION_ASCEND": "Route to Stairs", "INPUT_ACTION_INTERACT": "Interact",
		"INPUT_ACTION_CHARACTER": "Character Sheet", "INPUT_ACTION_MENU": "Menu / Back",
		"INPUT_KEY_SPACE": "Space", "INPUT_KEY_ENTER": "Enter", "INPUT_KEY_ESCAPE": "Esc",
		"INPUT_KEY_TAB": "Tab", "INPUT_KEY_BACKSPACE": "Backspace",
		"INPUT_PAD_BACK": "Back", "INPUT_PAD_START": "Start", "INPUT_PAD_BUTTON": "Button %d",
		"INPUT_DPAD_DIRECTION": "D-pad %s", "INPUT_LEFT_STICK_DIRECTION": "Left stick %s",
		"INPUT_RIGHT_STICK_DIRECTION": "Right stick %s", "INPUT_PAD_AXIS": "Axis %d %s",
		"EXPEDITION_CHOICE_TITLE": "Where should the expedition begin?",
		"EXPEDITION_CHOICE_DESC": "The rope leads to the best floor you have safely returned from. Starting over lets a weakened body gather strength again.",
		"BTN_ASCEND_ROPE": "Climb the rope — level %d",
		"BTN_ASCEND_ROPE_LOCKED": "The rope is not anchored yet",
		"BTN_ASCEND_BEGINNING": "Begin the ascent from level %d",
		"TITLE_NAME_CREATION": "Character Creation — Name",
		"TITLE_STAT_CREATION": "Character Creation — Soul Pattern",
		"CREATION_STEP_NAME": "Step 1 / 2 · Sex and name",
		"CREATION_STEP_STATS": "Step 2 / 2 · Attributes",
		"CREATION_POINTS_REMAIN": "Allocate every free point before finishing.",
		"NAME_PROMPT": "Enter character name", "NAME_PLACEHOLDER": "Enter a name",
		"SEX_FEMALE": "Female", "SEX_MALE": "Male",
		"SEX_CHOICE_HINT": "Sex: %s. Changes character-sheet and map artwork.",
		"NAME_EMPTY": "The name cannot be empty.", "FREE_POINTS": "Free points: %d",
		"SKELETON_PARAMETERS": "Parameters",
		"PARAM_DAMAGE": "Damage", "PARAM_ACCURACY": "Accuracy", "PARAM_HP": "HP",
		"PARAM_DODGE": "Dodge", "PARAM_MANA": "Mana", "PARAM_MANA_REGENERATION": "Mana regeneration",
		"PARAM_SPELL_POWER": "Spell Power",
		"PARAM_REGENERATION": "Regeneration", "PARAM_RANGED_DAMAGE": "Ranged Damage",
		"PARAM_RANGED_RANGE": "Ranged Range", "PARAM_VISION": "Vision",
		"PRIMARY_ATTRIBUTES": "PRIMARY ATTRIBUTES", "PARAMETERS": "PARAMETERS",
		"EQUIPMENT": "EQUIPMENT", "FORM_TRAIT": "FORM TRAIT",
		"MSG_AWAKENS": "%s awakens at the Bone Shelter.",
		"MSG_CHECKPOINT": "Level %d bone anchor activated.",
		"MSG_ENTER_FLOOR": "You enter level %d.",
		"MSG_SAFE_RETURN": "Safe return. Souls delivered to storage: %d.",
		"MSG_NOTHING_TO_USE": "There is nothing to use here. Find a Cradle, stairs or the path to base.",
		"MSG_BASE_UPGRADED": "The Bone Shelter reaches level %d. Maximum health increased.",
		"MSG_UPGRADE_NEEDS": "The upgrade requires %d souls.",
		"MSG_WAIT": "You stand still and let the enemies act.",
		"MSG_WAIT_COMPLETED": "Waiting complete: %d turns.",
		"MSG_WAIT_INTERRUPTED": "Waiting stopped after %d turns: an enemy was spotted.",
		"MSG_WAIT_INTERRUPTED_HP": "Waiting stopped after %d turns: health began to fall.",
		"MSG_WAIT_INTERRUPTED_RANGED": "Waiting stopped after %d turns: an arrow passed nearby.",
		"MSG_WAIT_INTERRUPTED_HEARING": "Waiting stopped after %d turns: a noise was heard.",
		"MSG_HEARING_MOVEMENT": "You hear movement nearby.",
		"MSG_HEARING_HIDDEN_ATTACK": "An attack came from the darkness.",
		"MSG_EXPLORE_ENEMY": "Exploration stopped: an enemy was spotted.",
		"MSG_EXPLORE_COMPLETE": "Every accessible part of the floor has been explored.",
		"MSG_EXPLORE_CANCELLED": "Automatic exploration stopped.",
		"MSG_EXPLORE_INTERRUPTED": "Exploration stopped: the route changed.",
		"MSG_ASCEND_LOCKED": "Find the stairs leading upward first.",
		"MSG_EXIT_DISCOVERED": "You discover the stairs leading upward.",
		"MSG_ASCEND_NO_PATH": "No safe route to the stairs could be found.",
		"MSG_ASCEND_STARTED": "You head for the stairs. The route will take %d turns.",
		"MSG_ASCEND_ARRIVED": "You reach the stairs. Use ascend again to enter the next level.",
		"MSG_ASCEND_INTERRUPTED": "Movement toward the stairs was interrupted.",
		"MSG_VICTORY": "You reach the first level. Beyond the door: light, and the question of what remains human.",
		"MSG_WALL": "The stone does not yield.",
		"MSG_BOSS_DOOR_LOCKED": "The heavy door is sealed by the Minotaur's power.",
		"MSG_DOOR_OPENED": "You open the door and step into the doorway.",
		"INSPECT_DOOR": "Closed room door",
		"INSPECT_DOOR_OPEN": "Open room door",
		"MSG_BOSS_DOOR_OPEN": " The door beyond the arena opens.",
		"MSG_PLAYER_MISS": "Missed %s (%d vs %d).",
		"MSG_ENEMY_KILLED": "%s destroyed. Souls gained: %d.",
		"MSG_PLAYER_HIT": "Hit %s: %d health remains.",
		"MSG_ENEMY_MISS": " %s misses (%d vs %d).", "MSG_ENEMY_HIT": " %s deals %d damage.",
		"MSG_HIDDEN_ENEMY_MISS": " A miss is heard in the darkness.",
		"MSG_HIDDEN_ENEMY_HIT": " A strike from the darkness deals %d damage.",
		"MSG_RANGED_NO_TARGET": "No visible target within %d cells for a shot.",
		"MSG_RANGED_TARGET_HIDDEN": "The selected target is hidden by the fog of war.",
		"MSG_RANGED_OUT_OF_RANGE": "The selected target is beyond bow range (%d cells).",
		"MSG_RANGED_LINE_BLOCKED": "There is no clear line of fire to the selected target.",
		"MSG_PLAYER_RANGED_MISS": "The arrow misses %s (%d vs %d).",
		"MSG_PLAYER_RANGED_HIT": "The arrow hits %s for %d damage; %d HP remains.",
		"MSG_PLAYER_RANGED_KILLED": "The arrow destroys %s for %d damage; gained %d souls.",
		"MSG_ENEMY_RANGED_MISS": " %s fires an arrow and misses (%d vs %d).",
		"MSG_ENEMY_RANGED_HIT": " %s hits with an arrow for %d damage.",
		"MSG_HIDDEN_RANGED_MISS": " An arrow flies out of the darkness and misses.",
		"MSG_HIDDEN_RANGED_HIT": " An arrow from the darkness deals %d damage.",
		"MSG_ITEM_EQUIPPED": "Equipped: %s.",
		"MSG_MANA_REGENERATED": " Mana regenerates: +%d.",
		"MSG_MAGIC_LOCKED": "Awaken magic and learn Magic Missile first.",
		"MSG_MAGIC_NO_MANA": "Magic Missile requires %d mana.",
		"MSG_MAGIC_OUT_OF_RANGE": "The selected target is beyond spell range (%d cells).",
		"MSG_MAGIC_LINE_BLOCKED": "A wall blocks the line to the selected target.",
		"MSG_MAGIC_NO_TARGET": "No Magic Missile target within %d cells.",
		"MSG_MAGIC_HIT": "Magic Missile hits %s for %d damage; %d HP remains.",
		"MSG_MAGIC_KILLED": "Magic Missile destroys %s for %d damage; gained %d souls.",
		"MSG_MAGIC_RICOCHET": " Ricochet — %s",
		"MSG_ITEM_UNEQUIPPED": "Unequipped and returned to inventory: %s.",
		"MSG_FORM_CANNOT_EQUIP_SELECTED": "The current form cannot use this slot.",
		"MSG_EQUIP_ITEM_MISSING": "The item “%s” is no longer in the inventory.",
		"MSG_EQUIP_SLOT_CHOICE_REQUIRED": "All compatible slots are occupied. Select the physical slot first: %s.",
		"MSG_EQUIP_SLOT_LOCKED": "“%s” cannot be equipped in “%s”: that slot is unavailable to %s.",
		"MSG_CHEST_OPENED": "Chest opened: %s · wood +%d · stone +%d.",
		"MSG_ITEM_DISMANTLED": "%s dismantled: wood +%d · stone +%d · cloth +%d.",
		"MSG_CRUSHER_REQUIRED": "An installed Crusher at base is required to dismantle items.",
		"MSG_WHETSTONE_REQUIRED": "An installed Whetstone at base is required to upgrade weapons.",
		"MSG_WEAPON_UPGRADED": "Upgrade succeeded: the weapon is now +%d.",
		"MSG_WEAPON_DOWNGRADED": "Failure damaged the weapon: its level fell to +%d.",
		"MSG_WEAPON_UNCHANGED": "The upgrade failed, but the weapon was unharmed.",
		"MSG_WEAPON_UPGRADE_RESOURCES": "An attempt requires %d stone, %d wood and %d cloth.",
		"MSG_ITEM_BOUND": "%s is now bound to the hero for %d souls and will survive death.",
		"MSG_ITEM_ALREADY_BOUND": "This item is already bound to the hero.",
		"MSG_ITEM_BIND_NEEDS_SOULS": "The ritual requires %d souls.",
		"MSG_RITUAL_TABLE_REQUIRED": "Binding is available only at a built Ritual Table.",
		"MSG_BOUND_ITEM_CANNOT_DISMANTLE": "A bound item cannot be dismantled.",
		"MSG_ITEMS_DISMANTLED_ALL": "Dismantled %d items · wood +%d · stone +%d · cloth +%d.",
		"MSG_DEATH": "The body is destroyed. Lost souls: %d, items: %d. You are a skeleton again.",
		"MSG_PATH_BASE": "The way down is open. Return to base to secure free souls.",
		"MSG_PATH_UP": "The stairs lead to level %d.",
		"MSG_TILE_START": "Level entry point.", "MSG_TURN_DONE": "Turn complete. Enemies draw closer.",
		"MSG_UNKNOWN_ITEM": "Unknown item.", "MSG_FORM_CANNOT_USE": "%s cannot yet use %s.",
		"MSG_GAME_LOADED": "Save loaded. Your journey continues.",
		"MSG_NO_ADJACENT_ENEMY": "There is no adjacent target to attack.",
		"MSG_ABILITY_SLOT_EMPTY": "No active ability is assigned to this slot.",
		"MSG_ABILITY_FORM_LOCKED": "The current form cannot use this ability yet.",
		"MSG_ABILITY_COOLDOWN": "%s is recovering: %d turns remaining.",
		"MSG_ABILITY_CANCELLED": "Target selection cancelled.",
		"MSG_DASH_NO_TARGET": "There is no free explored route for Dash.",
		"MSG_DASH_TARGETING": "Dash: choose a highlighted cell. Hold two directions for a diagonal; Enter confirms, Esc cancels.",
		"MSG_DASH_INVALID": "Dash cannot reach that cell.",
		"MSG_DASH_INVALID_HIDDEN": "Dash cannot target a hidden cell.",
		"MSG_DASH_INVALID_TILE": "That cell cannot be entered by Dash.",
		"MSG_DASH_INVALID_OCCUPIED": "A creature blocks the Dash path.",
		"MSG_DASH_INVALID_PATH": "A wall or closed door blocks the Dash path.",
		"MSG_DASH_COMPLETE": "Dash complete: moved %d cells.",
		"MSG_DASH_CHEST": " The chest was collected only at the Dash endpoint.",
		"MSG_ENEMY_DASH": " %s dashes and stops nearby.",
		"MSG_DOUBLE_ATTACK_SECOND": " Second strike: %s",
		"MSG_PASSIVE_DOUBLE_STRIKE": " Follow-up strike: %s",
		"MSG_CIRCULAR_ATTACK": "Circular Attack strikes every nearby enemy.",
		"MSG_CIRCULAR_NO_TARGETS": "There are no nearby targets for Circular Attack.",
		"MSG_EXIT_BLOCKED": "The stairs leading upward have not been discovered yet.",
		"MSG_FOOD_GAINED": " Food gained: %d.",
		"MSG_CAMP_EAT": "You make camp and eat 1 food. Satiety: %d%%.",
		"MSG_CAMP_NO_FOOD": "You need meat supplies to eat at camp.",
		"MSG_CAMP_FULL": "The flesh is already satiated.", "MSG_CAMP_SKELETON": "A skeleton has nothing to feed.",
		"MSG_HUNGER_TICK": " Satiety: %d%%.", "MSG_REGENERATED": " Regeneration restores %d HP.",
		"MSG_STARVATION": " Satiety is depleted: the body loses %d HP.",
		"MSG_CRADLE_APPEARED": "A Cradle was found on this floor.",
		"MSG_CRADLE_REQUIRED": "The body can only change inside a Cradle.",
		"MSG_CRADLE_TILE": "A Cradle stands before you. The next body stage can be purchased here.",
		"MSG_CRADLE_USED": "This Cradle has already reshaped the body and now lies silent.",
		"MSG_CRADLE_MAX": "The Cradle cannot improve the final form.",
		"MSG_CRADLE_NEEDS_SOULS": "The next stage requires %d carried souls.",
		"MSG_CRADLE_NEEDS_SOUL_LEVEL": "Soul Level %d required. Current Soul Level: %d.",
		"MSG_CRADLE_EVOLVED": "The Cradle reshapes the body into %s, consuming %d souls.",
		"CRADLE_CONFIRM_TITLE": "Confirm Evolution",
		"CRADLE_CONFIRM_DESC": "%s → %s\nCost: %d carried souls · carried: %d\nSoul Level: requires %d · current %d",
		"CRADLE_CONFIRM_BUTTON": "Evolve — %d souls",
		"CRADLE_CONFIRM_CANCEL": "Keep the current form",
		"CRADLE_CONFIRM_UNAVAILABLE": "Evolution unavailable",
		"CRADLE_CONFIRM_LEVEL_BLOCKED": "Requires Soul Level %d",
		"BOSS_WARNING_TITLE": "Ascend further?",
		"BOSS_WARNING_DESC": "You sense a powerful soul beyond the stairs.\nContinue the ascent to level %d?",
		"BOSS_WARNING_CONFIRM": "Ascend to level %d",
		"BOSS_WARNING_CANCEL": "Stay and prepare",
		"SIDEBAR_HUNGER": "Satiety: %d%%", "SIDEBAR_FOOD": "Food: %d",
		"CHARACTER_SURVIVAL": "Satiety: %d%% · Food: %d",
		"SKILLS_TITLE": "SKILLS", "SKILL_TAB_SKELETON": "Skeleton", "SKILL_TAB_ZOMBIE": "Zombie",
		"SKILL_TAB_GHOUL": "Ghoul", "SKILL_TAB_REVENANT": "Revenant",
		"SKILL_TAB_ALMOST_HUMAN": "Almost Human",
		"SKILL_TAB_LOCKED": "%s 🔒", "SKILL_LEVEL": "Lv. %d/%d", "SKILL_COST": "Cost: %d souls",
		"SKILL_KIND_ACTIVE": "ACTIVE · square", "SKILL_KIND_PASSIVE": "PASSIVE · circle",
		"SKILL_MAX": "Maximum level",
		"SKILL_BRANCH_BODY_BONES": "Body — Bones", "SKILL_BRANCH_BODY_FLESH": "Body — Flesh",
		"SKILL_BRANCH_BODY_GUT": "Body — Gut", "SKILL_BRANCH_BODY_CNS": "Body — CNS",
		"SKILL_BRANCH_BODY_APPEARANCE": "Body — Appearance", "SKILL_BRANCH_MAGIC": "Magic",
		"SKILL_BRANCH_MANEUVER": "Maneuver",
		"SKILL_BRANCH_COMBAT": "Combat", "SKILL_BRANCH_BODY": "Body",
		"SKILL_BRANCH_SENSES": "Senses", "SKILL_BRANCH_BASIC_ATTACK": "Basic attack",
		"SKILL_BRANCH_ABILITY": "Ability", "SKILL_BRANCH_APPEARANCE": "Appearance",
		"SKILL_DETAIL_TYPE_ACTIVE": "Type: active", "SKILL_DETAIL_TYPE_PASSIVE": "Type: passive",
		"SKILL_DETAIL_DESCRIPTION": "Description: %s", "SKILL_DETAIL_EFFECT": "Effect: %s",
		"SKILL_DETAIL_MANA": "Mana: %d", "SKILL_DETAIL_COOLDOWN": "Cooldown: %d turns",
		"SKILL_DETAIL_REQUIREMENT": "Requirement: %s", "SKILL_DETAIL_NOT_APPLICABLE": "none",
		"SKILL_DETAIL_STAGE": "%s stage", "SKILL_DETAIL_REQUIRES": "skill %s",
		"SKILL_STATUS_LEARN_AVAILABLE": "The skill is available to learn.",
		"SKILL_STATUS_UPGRADE_AVAILABLE": "The skill can be upgraded.",
		"SKILL_STATE_LOCKED": "Locked", "SKILL_STATE_AVAILABLE": "Available",
		"SKILL_STATE_LEARNED": "Learned", "SKILL_STATE_MAX": "MAX",
		"SKILL_ACTION_LEARN": "Learn — %d souls", "SKILL_ACTION_UPGRADE": "Upgrade — %d souls",
		"SKILL_ACTION_MAX": "Maximum level", "SKILL_ACTION_UNAVAILABLE": "Unavailable",
		"SKILL_STRONG_BONES": "Sturdy Bones", "SKILL_STRONG_BONES_DESC": "+3 maximum HP per level",
		"SKILL_FLEXIBLE_JOINTS": "Flexible Joints", "SKILL_FLEXIBLE_JOINTS_DESC": "+2 effective Agility",
		"SKILL_STRONG_SPINE": "Strong Spine", "SKILL_STRONG_SPINE_DESC": "+1 effective Vitality",
		"SKILL_FUNDAMENTALS": "Develop Fundamentals", "SKILL_FUNDAMENTALS_DESC": "+5 free attribute points",
		"SKILL_MAGIC_AWAKENING": "Magic Awakening", "SKILL_MAGIC_AWAKENING_DESC": "+5 mana and access to the magic branch",
		"SKILL_MAGIC_MISSILE": "Magic Missile", "SKILL_MAGIC_MISSILE_DESC": "10 mana · 3 damage +1/lvl · range 3",
		"SKILL_MAGIC_MISSILE_RANGE": "Long Missile", "SKILL_MAGIC_MISSILE_RANGE_DESC": "+2 cells of Magic Missile range",
		"SKILL_MAGIC_RICOCHET": "Ricochet", "SKILL_MAGIC_RICOCHET_DESC": "20% +5%/lvl · jumps to an enemy within 4",
		"SKILL_FLESH_REGENERATION": "Circulatory System", "SKILL_FLESH_REGENERATION_DESC": "Activates healing from the regeneration stat",
		"SKILL_MUSCLE_FIBERS": "Muscle Fibers", "SKILL_MUSCLE_FIBERS_DESC": "+1 effective Strength per level",
		"SKILL_STOMACH": "Stomach", "SKILL_STOMACH_DESC": "Unlocks Satiety and the camp Satiated status",
		"SKILL_EARS": "Ears", "SKILL_EARS_DESC": "Unlocks hearing and anonymous hidden-noise markers",
		"SKILL_SHARP_VISION": "Sharp Vision", "SKILL_SHARP_VISION_DESC": "+1 vision cell",
		"SKILL_NERVOUS_SYSTEM": "Nervous System", "SKILL_NERVOUS_SYSTEM_DESC": "Unlocks the camp Rested status",
		"SKILL_DASH": "Dash", "SKILL_DASH_DESC": "Move up to 3 cells in any direction along a clear line",
		"SKILL_DOUBLE_ATTACK": "Double Attack", "SKILL_DOUBLE_ATTACK_DESC": "Two independent strikes against one target in one turn",
		"SKILL_ALMOST_DOUBLE_STRIKE": "Follow-up Strike", "SKILL_ALMOST_DOUBLE_STRIKE_DESC": "10% +2 pp/lvl to repeat a basic attack",
		"SKILL_CIRCULAR_ATTACK": "Circular Attack", "SKILL_CIRCULAR_ATTACK_DESC": "A separate strike into all 8 adjacent cells",
		"SKILL_CHOOSE_APPEARANCE": "Choose Appearance", "SKILL_CHOOSE_APPEARANCE_DESC": "Choose the appearance of any unlocked body form",
		"SKILL_STRONG_BONES_DETAIL": "Reinforces the body's skeletal foundation and improves its survivability.",
		"SKILL_FLEXIBLE_JOINTS_DETAIL": "Flexible joints add 2 Agility to the actual body without changing the base attribute.",
		"SKILL_STRONG_SPINE_DETAIL": "A strong spine adds 1 Vitality to the actual body without changing the base attribute.",
		"SKILL_FUNDAMENTALS_DETAIL": "Developing the Almost Human body's fundamentals grants 5 free attribute points exactly once.",
		"SKILL_MAGIC_AWAKENING_DETAIL": "Awakens a mana reserve and opens the path to skeletal magic.",
		"SKILL_MAGIC_MISSILE_DETAIL": "Launches a guided magical projectile at a visible target.",
		"SKILL_MAGIC_MISSILE_RANGE_DETAIL": "Keeps a magical projectile stable across a greater distance.",
		"SKILL_MAGIC_RICOCHET_DETAIL": "Gives a Magic Missile a chance to jump to a second target.",
		"SKILL_FLESH_REGENERATION_DETAIL": "A developed circulatory system unlocks natural recovery for the actual Ghoul form and later bodies. If Satiety is unlocked, healing works only while it is above zero.",
		"SKILL_MUSCLE_FIBERS_DETAIL": "Each Muscle Fibers level adds 1 Strength to the actual Zombie form and later bodies without changing the base attribute.",
		"SKILL_STOMACH_DETAIL": "A developed stomach unlocks Satiety survival and the Satiated status after a true safe return to camp.",
		"SKILL_EARS_DETAIL": "Developed hearing lets the actual Ghoul form and later bodies notice nearby hidden movement and remember attacks from darkness with a ‘?’ marker. Cosmetic appearance does not unlock it.",
		"SKILL_DASH_DETAIL": "Rapidly moves the Ghoul along a clear visible line without stopping between cells.",
		"SKILL_DOUBLE_ATTACK_DETAIL": "Makes two independent basic strikes against the same adjacent target.",
		"SKILL_SHARP_VISION_DETAIL": "Develops the actual Zombie form's sight and expands the visible area by one cell.",
		"SKILL_NERVOUS_SYSTEM_DETAIL": "A learned Nervous System lets the actual Revenant form and later bodies prepare the Rested status on a safe return. Cosmetic appearance grants no eligibility.",
		"SKILL_ALMOST_DOUBLE_STRIKE_DETAIL": "Gives a basic attack a chance to repeat immediately against a surviving target.",
		"SKILL_CIRCULAR_ATTACK_DETAIL": "Attacks every enemy in the eight adjacent cells at once.",
		"SKILL_CHOOSE_APPEARANCE_DETAIL": "Changes appearance to any unlocked form without spending a turn.",
		"STATUS_RESTED": "Rested",
		"STATUS_RESTED_DESC": "+5 temporary HP · +1 physical damage · faster Dash and Double Attack",
		"STATUS_SATIATED": "Satiated",
		"STATUS_SATIATED_DESC": "+3 temporary HP · +1 HP regeneration · satiety does not decrease",
		"STATUS_TURNS": "%d turns remaining", "STATUS_MORE": "%d more statuses",
		"SKILL_SOULS": "Souls available: %d", "SKILL_FREE_STATS": "Free stats: %d",
		"ABILITY_BASIC_ATTACK": "Basic Attack", "ABILITY_BASIC_SHOT": "Basic Shot",
		"ABILITY_MAGIC_MISSILE": "Magic Missile",
		"ABILITY_DASH": "Dash", "ABILITY_DOUBLE_ATTACK": "Double Attack",
		"ABILITY_CIRCULAR_ATTACK": "Circular Attack", "ABILITY_EMPTY": "Empty",
		"ABILITY_CHOOSE_APPEARANCE": "Choose Appearance",
		"ABILITY_SLOT_ATTACK": "Primary Attack", "ABILITY_SLOT_ACTIVE_1": "Active 1",
		"ABILITY_SLOT_ACTIVE_2": "Active 2", "ABILITY_SLOT_ACTIVE_3": "Active 3",
		"ABILITY_ASSIGN_HINT": "Press to cycle through learned compatible abilities.",
		"ABILITY_ASSIGNED": "%s: assigned %s.",
		"ABILITY_HOTBAR_TOOLTIP": "%s · %s",
		"ABILITY_HOTBAR_COOLDOWN": "%s · %s · cooldown: %d turns",
		"ABILITY_ATTACK_FALLBACK": "%s\n%s: %d",
		"SKILL_BASE_ONLY": "Free attribute points can only be spent at base.",
		"SKILL_PURCHASED": "Skill %s increased to level %d.",
		"SKILL_NEEDS_SOULS": "The skill requires %d souls.",
		"SKILL_NEEDS_PREVIOUS": "Learn the previous skill first.",
		"SKILL_STAGE_LOCKED": "Reach this body stage first.",
		"SKILL_ALREADY_MAX": "The skill is already fully developed.",
		"EVOLUTION_MAX": "Final form reached",
		"EVOLUTION_NEXT": "%s · %d souls · Soul Level %d",
		"TITLE_FLOOR": "Level %d", "TITLE_BASE": "Bone Shelter",
		"TITLE_EXIT": "Level 1 — Exit",
		"HINT_DUNGEON": "WASD — move  |  F — primary attack  |  Q — active 1  |  T — wait  |  G — stairs",
		"HINT_BASE": "Stored souls are safe. Form and equipment persist until death.",
		"HINT_END": "End of the vertical slice", "SIDEBAR_FORM": "Form: %s",
		"SIDEBAR_HP": "Health: %d/%d", "SIDEBAR_CARRIED": "Free souls: %d",
		"SIDEBAR_BANKED": "Souls at base: %d", "SIDEBAR_EVOLUTION": "Evolution: %s",
		"SIDEBAR_SOULS_COMBINED": "Souls: carried %d · at base %d",
		"SOUL_COUNTER": "Souls: %d (%d)", "DUNGEON_SOUL_COUNTER": "%d (%d)",
		"SOUL_LEVEL_LABEL": "Soul Level: %d",
		"SOUL_LEVEL_APPEARANCE_LABEL": "Soul Level: %d\nForm: %s · Appearance: %s",
		"CHARACTER_SOUL_FORM_APPEARANCE": "Soul Level: %d\nForm: %s\nAppearance: %s",
		"APPEARANCE_TITLE": "Choose Appearance",
		"APPEARANCE_SUMMARY": "Actual form: %s\nSelected appearance: %s",
		"APPEARANCE_COSMETIC_HINT": "Cosmetic only. Stats, slots, satiety, and abilities use the actual form.",
		"APPEARANCE_CONFIRM": "Apply Appearance", "APPEARANCE_CANCEL": "Cancel [Esc / B]",
		"MSG_APPEARANCE_CHANGED": "Cosmetic appearance selected: %s.",
		"SIDEBAR_CRADLE_CHANCE": "Next Cradle chance: %d%%",
		"SIDEBAR_EQUIPMENT": "Equipment:", "UPGRADE_COST": "Reinforce shelter — %d souls",
		"CAMP_RESOURCES": "Materials: wood %d · stone %d · cloth %d",
		"BASE_RESOURCE_WOOD_TOOLTIP": "Wood: %d",
		"BASE_RESOURCE_STONE_TOOLTIP": "Stone: %d",
		"BASE_RESOURCE_CLOTH_TOOLTIP": "Cloth: %d",
		"BASE_SOULS_TOOLTIP": "Carried souls: %d · total: %d",
		"CAMP_MATERIAL_HINT": "Wood and stone come from chests; cloth comes from dismantled armor.",
		"CAMP_BUILD_CRUSHER": "Build Crusher — 5 wood · 5 stone",
		"CAMP_BUILD_WHETSTONE": "Install Whetstone — 10 wood · 10 stone · 5 cloth",
		"CAMP_BUILD_RITUAL_TABLE": "Build Ritual Table — 10 wood · 10 stone · 5 cloth",
		"CAMP_BUILD_CAMPFIRE": "Build Campfire — 3 wood · 3 stone · +1 Soul Level",
		"CAMP_BUILT_CRUSHER": "Crusher installed", "CAMP_BUILT_WHETSTONE": "Whetstone installed",
		"CAMP_BUILT_RITUAL_TABLE": "Ritual Table installed",
		"CAMP_BUILT_CAMPFIRE": "Campfire built · +1 Soul Level",
		"MSG_CAMPFIRE_SOUL_LEVEL": "The Campfire strengthens the soul. Soul Level: %d.",
		"MSG_CAMP_UPGRADE_BUILT": "Camp upgrade installed: %s.",
		"MSG_CAMP_UPGRADE_NEEDS": "Not enough materials to build this upgrade.",
		"MSG_CAMP_UPGRADE_EXISTS": "This upgrade is already installed.",
		"CHARACTER_TAB_SKILLS": "Skills", "CHARACTER_TAB_INVENTORY": "Inventory",
		"INVENTORY_SLOT_LOCKED": "locked", "INVENTORY_SELECT_ITEM": "Select an item or occupied slot.",
		"INVENTORY_PAGE": "Page %d / %d", "INVENTORY_EQUIP": "Equip",
		"INVENTORY_UNEQUIP": "Unequip", "INVENTORY_DISMANTLE": "Dismantle",
		"INVENTORY_DISMANTLE_ALL": "Dismantle all",
		"INVENTORY_DISMANTLE_ALL_CONFIRM_BUTTON": "Really all?",
		"INVENTORY_DISMANTLE_ALL_CONFIRM": "Press again to dismantle every unbound inventory item. Equipped and bound gear stays.",
		"INVENTORY_UPGRADE": "Upgrade weapon", "INVENTORY_UPGRADE_MAX": "Maximum upgrade +3",
		"INVENTORY_UPGRADE_WEAPON_ONLY": "Only weapons can be upgraded",
		"INVENTORY_UPGRADE_SELECT_SHORT": "Select weapon",
		"INVENTORY_UPGRADE_CHANCE": "Upgrade to +%d · %d%% chance",
		"INVENTORY_UPGRADE_CHANCE_COST": "To +%d · %d%% · %d stone, %d wood, %d cloth",
		"INVENTORY_ITEM_DETAIL": "Slot: %s\nDamage: %d · Accuracy: %d · HP: %d · Mana: %d",
		"INVENTORY_RANGED_ITEM_DETAIL": "Slot: %s\nRanged damage: %d · Accuracy: %d · Range: %d\nHP: %d · Mana: %d",
		"INVENTORY_WEAPON_CLASS": "Class: %s",
		"INVENTORY_FILTER_ALL": "All", "INVENTORY_EMPTY_FILTER": "No items in this category",
		"INVENTORY_FILTER_WEAPONS": "Weapons", "INVENTORY_FILTER_OFFHAND": "Off-hand",
		"INVENTORY_FILTER_ARMOR": "Armor", "INVENTORY_FILTER_ACCESSORIES": "Accessories",
		"INVENTORY_FILTER_BACKPACK": "Backpack",
		"INVENTORY_SELECTION_STALE": "The selection changed — select the item again.",
		"ACTION_PREFIX_OUTGOING": "↑ OUT:", "ACTION_PREFIX_INCOMING": "↓ IN:",
		"ACTION_PREFIX_LOOT": "▣ LOOT:", "ACTION_PREFIX_NEUTRAL": "· INFO:",
		"INVENTORY_SELECTED_PANEL": "SELECTED ITEM", "INVENTORY_EQUIPPED_PANEL": "EQUIPPED IN SLOT",
		"INVENTORY_EMPTY": "Empty", "INVENTORY_SLOT_LINE": "Slot: %s",
		"INVENTORY_LEVEL": "Upgrade: +%d", "INVENTORY_COUNT": "Count: ×%d",
		"INVENTORY_SALVAGE": "Salvage: wood %d · stone %d · cloth %d",
		"INVENTORY_SOUL_BONUS": "Soul bonus",
		"INVENTORY_SOUL_LEVEL_BONUS": "+%d Soul Level",
		"INVENTORY_PERMANENT_LOCKED": "Too cozy to take off",
		"INVENTORY_SOURCE_INVENTORY": "Inventory", "INVENTORY_SOURCE_EQUIPPED": "Equipped",
		"INVENTORY_SOURCE_LOCKED": "Locked slot",
		"INVENTORY_SERVICE_CRUSHER": "CRUSHER · ITEM DISMANTLING",
		"INVENTORY_SERVICE_WHETSTONE": "WHETSTONE · WEAPONS",
		"INVENTORY_SERVICE_RITUAL": "RITUAL TABLE · ITEM BINDING",
		"INVENTORY_CLOSE_SERVICE": "Close window [Esc / B]",
		"INVENTORY_BOUND_STATUS": "Bound to the hero · survives death",
		"INVENTORY_BOUND_SHORT": "bound",
		"INVENTORY_BIND_EXPLANATION": "The ritual binds one item instance to the hero. It will not be lost on death.",
		"INVENTORY_BIND_ACTION": "Bind — %d souls",
		"INVENTORY_BIND_ALREADY": "Already bound",
		"INVENTORY_BIND_TOOLTIP": "Bind one item instance to the hero for %d souls",
		"INVENTORY_BIND_ALREADY_DESC": "This item will already survive death",
		"INVENTORY_REASON_MAX": "This weapon is already upgraded to +3.",
		"INVENTORY_REASON_RESOURCES": "Requires 10 stone, 2 wood and 1 cloth.",
		"INVENTORY_PREVIOUS_PAGE": "Previous page", "INVENTORY_NEXT_PAGE": "Next page",
		"CAMP_OBJECT_CRUSHER": "Crusher\nOpen [Enter / A]",
		"CAMP_OBJECT_CRUSHER_TOOLTIP": "Open the item dismantling service",
		"CAMP_OBJECT_WHETSTONE": "Whetstone\nOpen [Enter / A]",
		"CAMP_OBJECT_WHETSTONE_TOOLTIP": "Open the weapon upgrade service",
		"CAMP_OBJECT_RITUAL_TABLE": "Ritual Table\nOpen [Enter / A]",
		"CAMP_OBJECT_RITUAL_TABLE_TOOLTIP": "Open the item binding service",
		"CAMP_OBJECT_STORAGE_CHEST": "Storage Chest\nOpen [Enter / A]",
		"CAMP_OBJECT_STORAGE_CHEST_TOOLTIP": "Open item storage",
		"STORAGE_TITLE": "STORAGE",
		"STORAGE_PLAYER_INVENTORY": "Player Inventory",
		"STORAGE_HEADING": "Storage",
		"STORAGE_INSTRUCTIONS": "Press a stack to move 1. Select a stack and press an arrow to move all.",
		"STORAGE_CLOSE": "Close [Esc / B]",
		"STORAGE_CLOSE_TOOLTIP": "Close the Storage window [Esc / B]",
		"STORAGE_FILTER_TOOLTIP": "Show category: %s",
		"STORAGE_INVENTORY_EMPTY": "No movable items in Player Inventory",
		"STORAGE_EMPTY": "Storage is empty",
		"STORAGE_EMPTY_FILTER": "No items in this category",
		"STORAGE_MOVE_ALL_RIGHT": "All →",
		"STORAGE_MOVE_ALL_LEFT": "← All",
		"STORAGE_MOVE_ALL_TO_STORAGE": "Move the entire selected stack to Storage",
		"STORAGE_MOVE_ALL_TO_INVENTORY": "Move the entire selected stack to Player Inventory",
		"STORAGE_SELECT_INVENTORY_STACK": "Select a stack in Player Inventory first",
		"STORAGE_SELECT_STORAGE_STACK": "Select a stack in Storage first",
		"STORAGE_MOVE_ONE_TOOLTIP": "%s: move 1 to %s",
		"STORAGE_MOVED_ONE": "%s: moved 1 item to %s.",
		"STORAGE_MOVED_COUNT": "Moved %d × %s to %s.",
		"STORAGE_SAVE_FAILED": "The game could not be saved, so the transfer was rolled back.",
		"STORAGE_REASON_UNBUILT": "Build the Storage Chest first.",
		"STORAGE_REASON_MISSING": "That stack is no longer in the selected list.",
		"STORAGE_REASON_INSUFFICIENT": "The stack does not contain enough items.",
		"STORAGE_REASON_COUNT": "Only a positive whole number can be moved.",
		"STORAGE_REASON_ITEM": "That item cannot be stored.",
		"STORAGE_REASON_FAILED": "The item could not be moved. Nothing was changed.",
		"MAGIC_MISSILE_TOOLTIP": "Damage %d · range %d · %d mana · 100%% hit · requires line of sight",
		"MAGIC_LOCKED_TOOLTIP": "Unlocked by the Magic Missile skill",
		"BASE_CENTER": "BONE SHELTER",
		"STORY_INTRO_1": "The skeleton wandered the lower levels for a long time, remembering neither name nor purpose.",
		"STORY_INTRO_2": "The first thing it found was an old poncho—almost absurd, but finally something of its own.",
		"STORY_INTRO_3": "Then something answered from inside the empty rib cage.",
		"STORY_DEATH": "After a time, the remains fell through the hatch into the quiet refuge below.",
		"STORY_CONTINUE": "Click to continue",
		"EXIT_CENTER": "LIGHT FROM THE SURFACE",
		"INSPECT_HEADER_AUTO": "INSPECTION · AUTO", "INSPECT_HEADER_SELECTED": "INSPECTION · SELECTED",
		"INSPECT_NOISE_SOURCE": "Noise source",
		"INSPECT_NONE": "Nothing interesting nearby.",
		"INSPECT_TARGET": "%s · %d cells",
		"INSPECT_ENEMY_STATS": "HP %d/%d · Damage %d · Accuracy %d · Vision %d",
		"INSPECT_ITEM_STATS": "Slot: %s · Damage %d · HP %d",
		"INSPECT_CHEST": "Chest", "INSPECT_CHEST_DESC": "Contains an item and possibly wood or stone.",
		"INSPECT_BASE": "Descent to base", "INSPECT_EXIT": "Stairs up",
		"INSPECT_START": "Level entry", "INSPECT_WALL": "Stone wall",
		"INSPECT_BOSS_DOOR": "Sealed arena door",
		"INSPECT_BOSS_DOOR_OPEN": "Open arena door",
		"INSPECT_CRADLE": "Cradle", "INSPECT_CRADLE_READY": "Next form: %s · Cost: %d souls · Soul Level: %d",
		"INSPECT_CRADLE_USED": "This floor's transformation has already been used",
		"INSPECT_FLOOR": "Stone floor", "INSPECT_VOID": "Impassable void",
	},
}

static var current_locale := "ru"
static var initialized := false


static func initialize_from_system() -> void:
	if initialized:
		return
	var system_locale := OS.get_locale_language().to_lower()
	current_locale = "en" if system_locale == "en" else "ru"
	initialized = true


static func toggle_locale() -> void:
	current_locale = "en" if current_locale == "ru" else "ru"
	initialized = true


static func set_locale(locale: String) -> void:
	if SUPPORTED_LOCALES.has(locale):
		current_locale = locale
		initialized = true


static func text(key: String, arguments: Array = []) -> String:
	var locale_strings: Dictionary = STRINGS.get(current_locale, STRINGS["ru"])
	var fallback_strings: Dictionary = STRINGS["ru"]
	var template := String(locale_strings.get(key, fallback_strings.get(key, key)))
	if arguments.is_empty():
		return template
	return template % arguments


static func language_code() -> String:
	return current_locale.to_upper()
