class_name Loc
extends RefCounted

## Lightweight runtime localization facade. Gameplay code only references keys;
## this can later be swapped for Godot Translation resources without touching it.

const SUPPORTED_LOCALES := ["ru", "en"]

const STRINGS := {
	"ru": {
		"ATTR_STRENGTH": "Сила", "ATTR_AGILITY": "Ловкость", "ATTR_PERCEPTION": "Восприятие",
		"ATTR_VITALITY": "Живучесть", "ATTR_WISDOM": "Мудрость",
		"FORM_SKELETON": "Скелет", "FORM_ZOMBIE": "Зомби", "FORM_GHOUL": "Гуль",
		"FORM_REVENANT": "Ревенант", "FORM_ALMOST_HUMAN": "Почти человек",
		"TRAIT_SKELETON": "Неуязвим к яду, хрупок в ближнем бою",
		"TRAIT_ZOMBIE": "Больше здоровья, но тело ещё неповоротливо",
		"TRAIT_GHOUL": "Сильные атаки и доступ к снаряжению для кистей",
		"TRAIT_REVENANT": "Управляет реликвиями и удерживает больше силы душ",
		"TRAIT_ALMOST_HUMAN": "Может использовать полный набор человеческого снаряжения",
		"SLOT_WEAPON": "Оружие", "SLOT_CHARM": "Талисман", "SLOT_ARMOR": "Броня",
		"SLOT_HANDS": "Кисти", "SLOT_RELIC": "Реликвия", "SLOT_OFFHAND": "Вторая рука",
		"ITEM_BONE_KNIFE": "Костяной нож", "ITEM_GRAVE_MACE": "Могильная булава",
		"ITEM_BONE_BOW": "Костяной лук",
		"ITEM_SOUL_LOCKET": "Медальон ловца", "ITEM_ROTTING_MAIL": "Сшитый панцирь",
		"ITEM_LEATHER_GLOVES": "Кожаные перчатки", "ITEM_HOLLOW_LANTERN": "Пустотный фонарь",
		"ITEM_PILGRIM_SHIELD": "Щит паломника",
		"CAMP_CRUSHER": "Дробилка", "CAMP_WHETSTONE": "Точильный камень",
		"CAMP_RITUAL_TABLE": "Ритуальный стол", "CAMP_CAMPFIRE": "Костёр",
		"ENEMY_GRAVE_RAT": "Могильная крыса", "ENEMY_HOLLOW_GUARD": "Пустой страж",
		"ENEMY_SOUL_LEECH": "Душеед", "ENEMY_SKELETAL_ARCHER": "Скелет-лучник",
		"ENEMY_MINOTAUR": "Минотавр",
		"GLYPH_GRAVE_RAT": "к", "GLYPH_HOLLOW_GUARD": "с", "GLYPH_SOUL_LEECH": "д",
		"GLYPH_SKELETAL_ARCHER": "л", "GLYPH_MINOTAUR": "М", "GLYPH_PLAYER": "И",
		"GLYPH_START": "S", "GLYPH_BASE": "Б",
		"GLYPH_CHEST": "▣",
		"BTN_START": "Начать вылазку", "BTN_CHARACTER_ACTION": "Перс. [E]",
		"BTN_INTERACT": "Действ.", "BTN_ASCEND": "Вверх [G]",
		"BTN_WAIT_ONE": "1 ход [T]", "BTN_WAIT_MANY": "%d ходов [T]",
		"WAIT_CYCLE_HINT": "Переключить ожидание: 1 → 10 → 100 ходов",
		"BTN_AUTO_EXPLORE": "Авто [X]", "BTN_AUTO_EXPLORE_STOP": "Стоп [X]",
		"BTN_ATTACK": "Атака [F]", "BTN_MAGIC": "Магия [Q]", "BTN_MAGIC_READY": "Стрела [Q]",
		"BTN_CAMP": "Привал [R]",
		"BTN_CHEAT_ADD_STATS": "ТЕСТ: +5 ОЧКОВ",
		"BTN_UPGRADE": "Укрепить костяной очаг", "BTN_CHARACTER": "Персонаж [E]",
		"BTN_CONTINUE": "Продолжить", "BTN_FINISH_CREATION": "Завершить создание",
		"BTN_BACK": "Вернуться [Esc]", "BTN_LANGUAGE": "Язык: %s", "BTN_MENU": "Меню",
		"BTN_NEW_GAME": "Начать новую игру", "BTN_NEW_GAME_CONFIRM": "Точно начать заново?",
		"BTN_EXIT": "Выйти из игры", "BTN_EXIT_CONFIRM": "Точно выйти?",
		"SETTINGS_TITLE": "Настройки", "SETTINGS_RADIUS": "Радиус автоосмотра: %d клеток",
		"SETTINGS_AUTO_DESC": "Без выбранной цели панель показывает ближайшего врага.\nЕсли врагов нет — ближайший предмет или важную клетку.",
		"BTN_SETTINGS_CLOSE": "Вернуться [Esc]", "SETTINGS_WINDOWED": "Режим: в окне",
		"SETTINGS_FULLSCREEN": "Режим: полный экран",
		"SETTINGS_INPUT_SUMMARY": "Назначения клавиатуры и геймпада можно изменить.",
		"SETTINGS_SOUND_ON": "Звук: включён", "SETTINGS_SOUND_OFF": "Звук: выключен",
		"SETTINGS_BACKGROUND_VOLUME": "Фон: %d%%", "SETTINGS_ACTIONS_VOLUME": "Действия: %d%%",
		"BTN_CONTROLS": "Настроить управление",
		"CONTROLS_TITLE": "Управление",
		"CONTROLS_SUBTITLE": "Выберите назначение, затем нажмите новую клавишу или кнопку геймпада.",
		"CONTROLS_ACTION_HEADER": "Действие", "CONTROLS_KEYBOARD_HEADER": "Клавиатура",
		"CONTROLS_GAMEPAD_HEADER": "Геймпад", "CONTROLS_BACK": "Вернуться [Esc / B]",
		"CONTROLS_RESET": "Сбросить по умолчанию", "CONTROLS_RESET_CONFIRM": "Подтвердить сброс",
		"CONTROLS_RESET_WARNING": "Повторное нажатие восстановит все стандартные назначения. Esc / B — отменить.",
		"CONTROLS_RESET_DONE": "Стандартные назначения восстановлены.",
		"CONTROLS_NOT_ASSIGNED": "Не назначено",
		"CONTROLS_WAIT_KEYBOARD": "Ожидание клавиши… Esc — отменить.",
		"CONTROLS_WAIT_GAMEPAD": "Ожидание кнопки или направления геймпада… B — отменить.",
		"CONTROLS_WRONG_DEVICE": "Ожидается ввод с устройства: %s.",
		"CONTROLS_CONFLICT": "%s уже назначено: %s. Enter / A — перенести сюда · Esc / B — отменить.",
		"CONTROLS_APPLIED": "%s назначено действию «%s».",
		"CONTROLS_CANCELLED": "Изменение отменено.",
		"CONTROLS_NAV_HINT": "Стрелки / D-pad — выбор · Enter / A — изменить · Esc / B — назад",
		"INPUT_ACTION_MOVE_UP": "Движение вверх", "INPUT_ACTION_MOVE_DOWN": "Движение вниз",
		"INPUT_ACTION_MOVE_LEFT": "Движение влево", "INPUT_ACTION_MOVE_RIGHT": "Движение вправо",
		"INPUT_ACTION_ATTACK": "Основная атака", "INPUT_ACTION_CAST_SPELL": "Активный слот 1",
		"INPUT_ACTION_WAIT": "Ждать ход", "INPUT_ACTION_AUTO_EXPLORE": "Исследовать этаж",
		"INPUT_ACTION_CAMP": "Привал",
		"INPUT_ACTION_ASCEND": "Путь к лестнице", "INPUT_ACTION_INTERACT": "Взаимодействие",
		"INPUT_ACTION_CHARACTER": "Лист персонажа", "INPUT_ACTION_MENU": "Меню / назад",
		"INPUT_KEY_SPACE": "Пробел", "INPUT_KEY_ENTER": "Enter", "INPUT_KEY_ESCAPE": "Esc",
		"INPUT_KEY_TAB": "Tab", "INPUT_KEY_BACKSPACE": "Backspace",
		"INPUT_PAD_BACK": "Назад", "INPUT_PAD_START": "Start", "INPUT_PAD_BUTTON": "Кнопка %d",
		"INPUT_DPAD_DIRECTION": "Крестовина %s", "INPUT_LEFT_STICK_DIRECTION": "Левый стик %s",
		"INPUT_RIGHT_STICK_DIRECTION": "Правый стик %s", "INPUT_PAD_AXIS": "Ось %d %s",
		"EXPEDITION_CHOICE_TITLE": "Откуда начать вылазку?",
		"EXPEDITION_CHOICE_DESC": "Верёвка ведёт на лучший уровень, с которого вы уже возвращались. Начало восхождения позволит заново собрать силы.",
		"BTN_ASCEND_ROPE": "Подняться по верёвке — уровень %d",
		"BTN_ASCEND_ROPE_LOCKED": "Верёвка ещё не закреплена",
		"BTN_ASCEND_BEGINNING": "Начать восхождение с %d-го уровня",
		"TITLE_NAME_CREATION": "Создание персонажа — имя",
		"TITLE_STAT_CREATION": "Создание персонажа — структура души",
		"NAME_PROMPT": "Как звали это существо при жизни?", "NAME_PLACEHOLDER": "Введите имя",
		"NAME_EMPTY": "Имя не может быть пустым.", "FREE_POINTS": "Свободных очков: %d",
		"SKELETON_PARAMETERS": "Параметры скелета",
		"PARAM_DAMAGE": "Урон", "PARAM_ACCURACY": "Точность", "PARAM_HP": "HP",
		"PARAM_DODGE": "Уклонение", "PARAM_MANA": "Мана", "PARAM_MANA_REGENERATION": "Регенерация маны",
		"PARAM_SPELL_POWER": "Сила заклинаний", "PARAM_REGENERATION": "Регенерация",
		"PARAM_RANGED_DAMAGE": "Дальний урон", "PARAM_RANGED_RANGE": "Дальность стрельбы",
		"PARAM_VISION": "Обзор", "PRIMARY_ATTRIBUTES": "ОСНОВНЫЕ ХАРАКТЕРИСТИКИ",
		"PARAMETERS": "ПАРАМЕТРЫ", "EQUIPMENT": "СНАРЯЖЕНИЕ", "FORM_TRAIT": "ОСОБЕННОСТЬ ФОРМЫ",
		"MSG_AWAKENS": "%s пробуждается у Костяного очага.",
		"MSG_CHECKPOINT": "Активирован костяной якорь %d-го уровня.",
		"MSG_ENTER_FLOOR": "Вы вошли на %d-й уровень. Выход к поверхности где-то впереди.",
		"MSG_SAFE_RETURN": "Безопасное возвращение. В хранилище доставлено душ: %d.",
		"MSG_NOTHING_TO_USE": "Здесь не с чем взаимодействовать. Ищите Колыбель, лестницу или путь на базу.",
		"MSG_BASE_UPGRADED": "Костяной очаг улучшен до уровня %d. Максимум здоровья вырос.",
		"MSG_UPGRADE_NEEDS": "Для улучшения нужно душ: %d.",
		"MSG_WAIT": "Вы замираете и позволяете врагам сделать ход.",
		"MSG_WAIT_COMPLETED": "Ожидание завершено: %d ходов.",
		"MSG_WAIT_INTERRUPTED": "Ожидание прервано через %d ходов: замечен враг.",
		"MSG_WAIT_INTERRUPTED_HP": "Ожидание прервано через %d ходов: здоровье начало снижаться.",
		"MSG_WAIT_INTERRUPTED_RANGED": "Ожидание прервано через %d ходов: рядом пролетела стрела.",
		"MSG_EXPLORE_ENEMY": "Исследование прервано: замечен враг.",
		"MSG_EXPLORE_COMPLETE": "Все доступные участки этажа исследованы.",
		"MSG_EXPLORE_CANCELLED": "Автоматическое исследование остановлено.",
		"MSG_EXPLORE_INTERRUPTED": "Исследование прервано: путь изменился.",
		"MSG_ASCEND_LOCKED": "Сначала найдите лестницу наверх.",
		"MSG_EXIT_DISCOVERED": "Вы обнаружили лестницу наверх.",
		"MSG_ASCEND_NO_PATH": "До лестницы не удалось построить безопасный путь.",
		"MSG_ASCEND_STARTED": "Вы направляетесь к лестнице. Путь займёт %d ходов.",
		"MSG_ASCEND_ARRIVED": "Вы дошли до лестницы. Нажмите подъём ещё раз, чтобы перейти на следующий уровень.",
		"MSG_ASCEND_INTERRUPTED": "Движение к лестнице прервано.",
		"MSG_VICTORY": "Вы достигли первого уровня. За дверью — свет и вопрос: осталось ли в вас что-то человеческое?",
		"MSG_WALL": "Камень не уступает.",
		"MSG_BOSS_DOOR_LOCKED": "Тяжёлая дверь запечатана силой Минотавра.",
		"MSG_BOSS_DOOR_OPEN": " Дверь за ареной открывается.",
		"MSG_PLAYER_MISS": "Промах по цели «%s» (%d против %d).",
		"MSG_ENEMY_KILLED": "%s уничтожен. Получено душ: %d.",
		"MSG_PLAYER_HIT": "Удар по цели «%s»: осталось %d здоровья.",
		"MSG_ENEMY_MISS": " %s промахивается (%d против %d).",
		"MSG_ENEMY_HIT": " %s наносит %d урона.", "MSG_ITEM_EQUIPPED": "Экипировано: %s.",
		"MSG_RANGED_NO_TARGET": "В радиусе %d клеток нет видимой цели для выстрела.",
		"MSG_RANGED_TARGET_HIDDEN": "Выбранная цель скрыта туманом войны.",
		"MSG_RANGED_OUT_OF_RANGE": "Выбранная цель вне дальности лука (%d клеток).",
		"MSG_RANGED_LINE_BLOCKED": "Между вами и выбранной целью нет прямой линии огня.",
		"MSG_PLAYER_RANGED_MISS": "Стрела не попадает в цель «%s» (%d против %d).",
		"MSG_PLAYER_RANGED_HIT": "Стрела поражает «%s»: %d урона, осталось %d HP.",
		"MSG_PLAYER_RANGED_KILLED": "Стрела уничтожает «%s»: %d урона, получено душ %d.",
		"MSG_ENEMY_RANGED_MISS": " %s выпускает стрелу и промахивается (%d против %d).",
		"MSG_ENEMY_RANGED_HIT": " %s попадает стрелой: %d урона.",
		"MSG_HIDDEN_RANGED_MISS": " Из темноты прилетает стрела и проходит мимо.",
		"MSG_HIDDEN_RANGED_HIT": " Стрела из темноты наносит %d урона.",
		"MSG_MANA_REGENERATED": " Мана восстанавливается: +%d.",
		"MSG_MAGIC_LOCKED": "Сначала пробудите магию и изучите Магическую стрелу.",
		"MSG_MAGIC_NO_MANA": "Для Магической стрелы нужно %d маны.",
		"MSG_MAGIC_OUT_OF_RANGE": "Выбранная цель вне дальности заклинания (%d клеток).",
		"MSG_MAGIC_LINE_BLOCKED": "Между вами и выбранной целью проходит стена.",
		"MSG_MAGIC_NO_TARGET": "В радиусе %d клеток нет цели для Магической стрелы.",
		"MSG_MAGIC_HIT": "Магическая стрела поражает «%s»: %d урона, осталось %d HP.",
		"MSG_MAGIC_KILLED": "Магическая стрела уничтожает «%s»: %d урона, получено душ %d.",
		"MSG_MAGIC_RICOCHET": " Рикошет — %s",
		"MSG_ITEM_UNEQUIPPED": "Снято и возвращено в инвентарь: %s.",
		"MSG_FORM_CANNOT_EQUIP_SELECTED": "Текущая форма не может использовать этот слот.",
		"MSG_CHEST_OPENED": "Сундук открыт: %s · дерево +%d · камень +%d.",
		"MSG_ITEM_DISMANTLED": "%s разобрано: дерево +%d · камень +%d · ткань +%d.",
		"MSG_CRUSHER_REQUIRED": "Для разбора нужна установленная дробилка на базе.",
		"MSG_WHETSTONE_REQUIRED": "Для улучшения нужен установленный точильный камень на базе.",
		"MSG_WEAPON_UPGRADED": "Улучшение удалось: оружие теперь +%d.",
		"MSG_WEAPON_DOWNGRADED": "Неудача повредила оружие: уровень снижен до +%d.",
		"MSG_WEAPON_UNCHANGED": "Улучшение не удалось, но оружие не пострадало.",
		"MSG_WEAPON_UPGRADE_RESOURCES": "Для попытки нужно %d камня, %d дерева и %d ткани.",
		"MSG_ITEM_BOUND": "%s теперь связано с героем за %d душ и сохранится после смерти.",
		"MSG_ITEM_ALREADY_BOUND": "Эта вещь уже связана с героем.",
		"MSG_ITEM_BIND_NEEDS_SOULS": "Для ритуала нужно душ: %d.",
		"MSG_RITUAL_TABLE_REQUIRED": "Привязка доступна только у построенного ритуального стола.",
		"MSG_BOUND_ITEM_CANNOT_DISMANTLE": "Связанную вещь нельзя разобрать.",
		"MSG_ITEMS_DISMANTLED_ALL": "Разобрано предметов: %d · дерево +%d · камень +%d · ткань +%d.",
		"MSG_DEATH": "Тело разрушено. Потеряно душ: %d, предметов: %d. Вы снова скелет.",
		"MSG_PATH_BASE": "Путь вниз открыт. Можно вернуться на базу и сохранить свободные души.",
		"MSG_PATH_UP": "Лестница ведёт к поверхности, на %d-й уровень.",
		"MSG_TILE_START": "Точка входа в уровень.", "MSG_TURN_DONE": "Ход завершён. Враги приблизились.",
		"MSG_UNKNOWN_ITEM": "Неизвестный предмет.",
		"MSG_FORM_CANNOT_USE": "Форма «%s» ещё не может использовать: %s.",
		"MSG_GAME_LOADED": "Сохранение загружено. Вы снова у Костяного очага.",
		"MSG_NO_ADJACENT_ENEMY": "Рядом нет цели для атаки.",
		"MSG_ABILITY_SLOT_EMPTY": "В этом слоте нет закреплённого активного навыка.",
		"MSG_ABILITY_FORM_LOCKED": "Текущая форма ещё не может использовать этот навык.",
		"MSG_ABILITY_CANCELLED": "Выбор цели отменён.",
		"MSG_DASH_NO_TARGET": "Для рывка нет свободного исследованного пути.",
		"MSG_DASH_TARGETING": "Рывок: выберите подсвеченную клетку. Два направления одновременно — диагональ; Enter — подтвердить, Esc — отменить.",
		"MSG_DASH_INVALID": "В эту клетку нельзя совершить рывок.",
		"MSG_DASH_COMPLETE": "Рывок завершён: пройдено клеток — %d.",
		"MSG_DASH_CHEST": " Сундук подобран только в конечной клетке рывка.",
		"MSG_ENEMY_DASH": " %s совершает рывок и останавливается рядом.",
		"MSG_DOUBLE_ATTACK_SECOND": " Второй удар: %s",
		"MSG_PASSIVE_DOUBLE_STRIKE": " Повторный удар: %s",
		"MSG_CIRCULAR_ATTACK": "Круговая атака поражает всех врагов рядом.",
		"MSG_CIRCULAR_NO_TARGETS": "Для круговой атаки рядом нет целей.",
		"MSG_EXIT_BLOCKED": "Лестница наверх ещё не обнаружена.",
		"MSG_FOOD_GAINED": " Получено еды: %d.",
		"MSG_CAMP_EAT": "Вы устраиваете привал и съедаете 1 еду. Голод: %d%%.",
		"MSG_CAMP_NO_FOOD": "Для привала с едой нужны мясные припасы.",
		"MSG_CAMP_FULL": "Плоть уже насыщена.", "MSG_CAMP_SKELETON": "Скелету нечего кормить.",
		"MSG_HUNGER_TICK": " Голод: %d%%.", "MSG_REGENERATED": " Регенерация восстанавливает %d HP.",
		"MSG_STARVATION": " Голод истощает тело: потеряно %d HP.",
		"MSG_CRADLE_APPEARED": "На этом уровне обнаружена Колыбель.",
		"MSG_CRADLE_REQUIRED": "Изменить форму можно только внутри Колыбели.",
		"MSG_CRADLE_TILE": "Перед вами Колыбель. Здесь можно оплатить следующую стадию формы.",
		"MSG_CRADLE_USED": "Эта Колыбель уже преобразила тело и теперь молчит.",
		"MSG_CRADLE_MAX": "Колыбель не может улучшить предельную форму.",
		"MSG_CRADLE_NEEDS_SOULS": "Для следующей стадии Колыбели нужно переносимых душ: %d.",
		"MSG_CRADLE_EVOLVED": "Колыбель перестраивает тело в форму «%s», поглощая %d душ.",
		"CRADLE_CONFIRM_TITLE": "Подтвердите эволюцию",
		"CRADLE_CONFIRM_DESC": "%s → %s\nСтоимость: %d переносимых душ\nС собой: %d душ",
		"CRADLE_CONFIRM_BUTTON": "Эволюционировать — %d душ",
		"CRADLE_CONFIRM_CANCEL": "Остаться в текущей форме",
		"CRADLE_CONFIRM_UNAVAILABLE": "Эволюция недоступна",
		"BOSS_WARNING_TITLE": "Подняться выше?",
		"BOSS_WARNING_DESC": "Вы ощущаете сильную душу за лестницей.\nПродолжить восхождение на %d-й уровень?",
		"BOSS_WARNING_CONFIRM": "Подняться на %d-й уровень",
		"BOSS_WARNING_CANCEL": "Остаться и подготовиться",
		"SIDEBAR_HUNGER": "Голод: %d%%", "SIDEBAR_FOOD": "Еда: %d",
		"CHARACTER_SURVIVAL": "Голод: %d%% · Еда: %d",
		"SKILLS_TITLE": "НАВЫКИ", "SKILL_TAB_SKELETON": "Скелет", "SKILL_TAB_ZOMBIE": "Зомби",
		"SKILL_TAB_GHOUL": "Гуль", "SKILL_TAB_REVENANT": "Ревенант",
		"SKILL_TAB_ALMOST_HUMAN": "Почти человек",
		"SKILL_TAB_LOCKED": "%s 🔒", "SKILL_LEVEL": "Ур. %d/%d", "SKILL_COST": "Цена: %d душ",
		"SKILL_KIND_ACTIVE": "АКТИВНЫЙ · квадрат", "SKILL_KIND_PASSIVE": "ПАССИВНЫЙ · круг",
		"SKILL_MAX": "Максимальный уровень", "SKILL_COMING_SOON": "СКОРО\nПустая ячейка",
		"SKILL_STRONG_BONES": "Крепкие кости", "SKILL_STRONG_BONES_DESC": "+3 максимального HP за уровень",
		"SKILL_FUNDAMENTALS": "Развитие основ", "SKILL_FUNDAMENTALS_DESC": "+5 свободных очков характеристик",
		"SKILL_MAGIC_AWAKENING": "Пробуждение магии", "SKILL_MAGIC_AWAKENING_DESC": "+5 маны и доступ к магической ветке",
		"SKILL_MAGIC_MISSILE": "Магическая стрела", "SKILL_MAGIC_MISSILE_DESC": "10 маны · урон 3 +1/ур. · дальность 3",
		"SKILL_MAGIC_MISSILE_RANGE": "Дальняя стрела", "SKILL_MAGIC_MISSILE_RANGE_DESC": "+2 клетки дальности Магической стрелы",
		"SKILL_MAGIC_RICOCHET": "Рикошет", "SKILL_MAGIC_RICOCHET_DESC": "20% +5%/ур. · прыжок к врагу в радиусе 4",
		"SKILL_FLESH_REGENERATION": "Регенерация", "SKILL_FLESH_REGENERATION_DESC": "Активирует лечение по параметру регенерации (база зомби: +1)",
		"SKILL_SHARP_VISION": "Острое зрение", "SKILL_SHARP_VISION_DESC": "+1 клетка обзора за уровень",
		"SKILL_DASH": "Рывок", "SKILL_DASH_DESC": "1–3 клетки по прямой, включая диагонали",
		"SKILL_DOUBLE_ATTACK": "Двойная атака", "SKILL_DOUBLE_ATTACK_DESC": "Два независимых удара по одной цели за ход",
		"SKILL_ALMOST_DOUBLE_STRIKE": "Повторный удар", "SKILL_ALMOST_DOUBLE_STRIKE_DESC": "10% +2 п.п./ур. повторить обычную атаку",
		"SKILL_CIRCULAR_ATTACK": "Круговая атака", "SKILL_CIRCULAR_ATTACK_DESC": "Отдельный удар по всем 8 соседним клеткам",
		"SKILL_SOULS": "Доступно душ: %d", "SKILL_FREE_STATS": "Свободные статы: %d",
		"ABILITY_BASIC_ATTACK": "Базовая атака", "ABILITY_BASIC_SHOT": "Выстрел",
		"ABILITY_MAGIC_MISSILE": "Магическая стрела",
		"ABILITY_DASH": "Рывок", "ABILITY_DOUBLE_ATTACK": "Двойная атака",
		"ABILITY_CIRCULAR_ATTACK": "Круговая атака", "ABILITY_EMPTY": "Пусто",
		"ABILITY_SLOT_ATTACK": "Основная атака", "ABILITY_SLOT_ACTIVE_1": "Активный 1",
		"ABILITY_SLOT_ACTIVE_2": "Активный 2", "ABILITY_SLOT_ACTIVE_3": "Активный 3",
		"ABILITY_ASSIGN_HINT": "Нажмите, чтобы выбрать следующий изученный совместимый навык.",
		"ABILITY_ASSIGNED": "%s: закреплено «%s».",
		"ABILITY_HOTBAR_TOOLTIP": "%s · %s",
		"SKILL_BASE_ONLY": "Распределять свободные характеристики можно только на базе.",
		"SKILL_PURCHASED": "Навык «%s» повышен до уровня %d.",
		"SKILL_NEEDS_SOULS": "Для навыка нужно душ: %d.",
		"SKILL_NEEDS_PREVIOUS": "Сначала изучите предыдущий навык.",
		"SKILL_STAGE_LOCKED": "Сначала достигните этой стадии тела.",
		"SKILL_ALREADY_MAX": "Навык уже развит полностью.",
		"EVOLUTION_MAX": "Предельная форма достигнута",
		"EVOLUTION_NEXT": "%s · %d душ в Колыбели",
		"TITLE_FLOOR": "Уровень %d — путь к поверхности", "TITLE_BASE": "Уровень 100 — Костяной очаг",
		"TITLE_EXIT": "Уровень 1 — Выход",
		"HINT_DUNGEON": "WASD — ход  |  F — основная атака  |  Q — активный 1  |  T — ждать  |  G — лестница",
		"HINT_BASE": "Сохранённые души не теряются. Форма и снаряжение сохраняются до смерти.",
		"HINT_END": "Конец вертикального среза", "SIDEBAR_FORM": "Форма: %s",
		"SIDEBAR_HP": "Здоровье: %d/%d", "SIDEBAR_CARRIED": "Свободные души: %d",
		"SIDEBAR_BANKED": "Души на базе: %d", "SIDEBAR_EVOLUTION": "Эволюция: %s",
		"SIDEBAR_SOULS_COMBINED": "Души: с собой %d · на базе %d",
		"SOUL_COUNTER": "Души: %d (%d всего)",
		"SIDEBAR_CRADLE_CHANCE": "Следующий шанс Колыбели: %d%%",
		"SIDEBAR_EQUIPMENT": "Снаряжение:", "UPGRADE_COST": "Укрепить очаг — %d душ",
		"CAMP_RESOURCES": "Материалы: дерево %d · камень %d · ткань %d",
		"CAMP_MATERIAL_HINT": "Дерево и камень — в сундуках; ткань — из разбора брони.",
		"CAMP_INSTALLED": "Установленные улучшения:", "CAMP_INSTALLED_NONE": "пока нет",
		"CAMP_BUILD_CRUSHER": "Построить дробилку — 5 дерева · 5 камня",
		"CAMP_BUILD_WHETSTONE": "Поставить точильный камень — 10 дерева · 10 камня · 5 ткани",
		"CAMP_BUILD_RITUAL_TABLE": "Построить ритуальный стол — 10 дерева · 10 камня · 5 ткани",
		"CAMP_BUILD_CAMPFIRE": "Сложить костёр — 3 дерева · 3 камня · +1 HP",
		"CAMP_BUILT_CRUSHER": "Дробилка установлена", "CAMP_BUILT_WHETSTONE": "Точильный камень установлен",
		"CAMP_BUILT_RITUAL_TABLE": "Ритуальный стол установлен",
		"CAMP_BUILT_CAMPFIRE": "Костёр сложен · +1 HP",
		"MSG_CAMP_UPGRADE_BUILT": "В лагере установлено улучшение: %s.",
		"MSG_CAMP_UPGRADE_NEEDS": "Для постройки не хватает материалов.",
		"MSG_CAMP_UPGRADE_EXISTS": "Это улучшение уже установлено.",
		"CHARACTER_TAB_SKILLS": "Навыки", "CHARACTER_TAB_INVENTORY": "Инвентарь",
		"INVENTORY_SLOT_LOCKED": "закрыто", "INVENTORY_SELECT_ITEM": "Выберите вещь или занятый слот.",
		"INVENTORY_PAGE": "Страница %d / %d", "INVENTORY_EQUIP": "Экипировать",
		"INVENTORY_UNEQUIP": "Снять", "INVENTORY_DISMANTLE": "Разобрать",
		"INVENTORY_DISMANTLE_ALL": "Разобрать всё",
		"INVENTORY_DISMANTLE_ALL_CONFIRM_BUTTON": "Точно всё?",
		"INVENTORY_DISMANTLE_ALL_CONFIRM": "Повторное нажатие разберёт все несвязанные вещи в инвентаре. Экипировка и связанные вещи останутся.",
		"INVENTORY_UPGRADE": "Улучшить оружие", "INVENTORY_UPGRADE_MAX": "Максимальное улучшение +3",
		"INVENTORY_UPGRADE_WEAPON_ONLY": "Улучшать можно только оружие",
		"INVENTORY_UPGRADE_SELECT_SHORT": "Выбрать оружие",
		"INVENTORY_UPGRADE_CHANCE": "Улучшить до +%d · шанс %d%%",
		"INVENTORY_UPGRADE_CHANCE_COST": "До +%d · %d%% · %d камня, %d дерева, %d ткани",
		"INVENTORY_ITEM_DETAIL": "Слот: %s\nУрон: %d · Точность: %d · HP: %d · Мана: %d",
		"INVENTORY_RANGED_ITEM_DETAIL": "Слот: %s\nДальний урон: %d · Точность: %d · Дальность: %d\nHP: %d · Мана: %d",
		"INVENTORY_FILTER_ALL": "Все", "INVENTORY_EMPTY_FILTER": "В этой категории нет вещей",
		"INVENTORY_SELECTED_PANEL": "ВЫБРАННАЯ ВЕЩЬ", "INVENTORY_EQUIPPED_PANEL": "НАДЕТО В СЛОТЕ",
		"INVENTORY_EMPTY": "Пусто", "INVENTORY_SLOT_LINE": "Слот: %s",
		"INVENTORY_LEVEL": "Улучшение: +%d", "INVENTORY_COUNT": "Количество: ×%d",
		"INVENTORY_SALVAGE": "Разбор: дерево %d · камень %d · ткань %d",
		"INVENTORY_SOUL_BONUS": "Бонус душ",
		"INVENTORY_SOURCE_INVENTORY": "Инвентарь", "INVENTORY_SOURCE_EQUIPPED": "Надето",
		"INVENTORY_SOURCE_LOCKED": "Закрытый слот",
		"INVENTORY_SERVICE_CRUSHER": "ДРОБИЛКА · РАЗБОР ВЕЩЕЙ",
		"INVENTORY_SERVICE_WHETSTONE": "ТОЧИЛЬНЫЙ КАМЕНЬ · ОРУЖИЕ",
		"INVENTORY_SERVICE_RITUAL": "РИТУАЛЬНЫЙ СТОЛ · ПРИВЯЗКА ВЕЩЕЙ",
		"INVENTORY_BOUND_STATUS": "Связано с героем · сохраняется после смерти",
		"INVENTORY_BOUND_SHORT": "связано",
		"INVENTORY_BIND_EXPLANATION": "Ритуал связывает один экземпляр вещи с героем. Он не потеряется после смерти.",
		"INVENTORY_BIND_ACTION": "Связать — %d душ",
		"INVENTORY_BIND_ALREADY": "Уже связано",
		"INVENTORY_BIND_TOOLTIP": "Связать один экземпляр вещи с героем за %d душ",
		"INVENTORY_BIND_ALREADY_DESC": "Эта вещь уже сохранится после смерти",
		"INVENTORY_REASON_MAX": "Оружие уже улучшено до +3.",
		"INVENTORY_REASON_RESOURCES": "Не хватает 10 камня, 2 дерева и 1 ткани.",
		"INVENTORY_PREVIOUS_PAGE": "Предыдущая страница", "INVENTORY_NEXT_PAGE": "Следующая страница",
		"CAMP_OBJECT_CRUSHER": "Дробилка\nОткрыть [Enter / A]",
		"CAMP_OBJECT_CRUSHER_TOOLTIP": "Открыть меню разборки вещей",
		"CAMP_OBJECT_WHETSTONE": "Точильный камень\nОткрыть [Enter / A]",
		"CAMP_OBJECT_WHETSTONE_TOOLTIP": "Открыть меню улучшения оружия",
		"CAMP_OBJECT_RITUAL_TABLE": "Ритуальный стол\nОткрыть [Enter / A]",
		"CAMP_OBJECT_RITUAL_TABLE_TOOLTIP": "Открыть меню привязки вещей",
		"MAGIC_MISSILE_TOOLTIP": "Урон %d · дальность %d · %d маны · попадание 100%% · нужна прямая видимость",
		"MAGIC_LOCKED_TOOLTIP": "Открывается навыком «Магическая стрела»",
		"BASE_CENTER": "КОСТЯНОЙ ОЧАГ", "BASE_SUBTITLE": "Отсюда начинается каждое новое тело",
		"STORY_INTRO_1": "Скелет долго бродил по нижним уровням, не помня ни имени, ни цели.",
		"STORY_INTRO_2": "Первой найденной вещью оказалось старое пончо. Почти нелепая, но уже своя одежда.",
		"STORY_INTRO_3": "А затем внутри пустой грудной клетки что-то отозвалось.",
		"STORY_DEATH": "Спустя время останки провалились через люк обратно в тихий закуток.",
		"STORY_CONTINUE": "Нажмите, чтобы продолжить",
		"EXIT_CENTER": "СВЕТ С ПОВЕРХНОСТИ",
		"INSPECT_HEADER_AUTO": "ОСМОТР · АВТО", "INSPECT_HEADER_SELECTED": "ОСМОТР · ВЫБРАНО",
		"INSPECT_NONE": "В радиусе %d клеток ничего интересного.",
		"INSPECT_TARGET": "%s · %d кл.",
		"INSPECT_ENEMY_STATS": "HP %d/%d · Урон %d · Точность %d · Обзор %d",
		"INSPECT_ITEM_STATS": "Слот: %s · Урон %d · HP %d",
		"INSPECT_CHEST": "Сундук", "INSPECT_CHEST_DESC": "Внутри предмет и, возможно, дерево или камень.",
		"INSPECT_BASE": "Спуск на базу", "INSPECT_EXIT": "Подъём наверх",
		"INSPECT_START": "Точка входа", "INSPECT_WALL": "Каменная стена",
		"INSPECT_BOSS_DOOR": "Запечатанная дверь арены",
		"INSPECT_BOSS_DOOR_OPEN": "Открытая дверь арены",
		"INSPECT_CRADLE": "Колыбель", "INSPECT_CRADLE_READY": "Следующая форма: %s · Цена: %d душ",
		"INSPECT_CRADLE_USED": "Преобразование на этом уровне уже совершено",
		"INSPECT_FLOOR": "Каменный пол", "INSPECT_VOID": "Непроходимая пустота",
	},
	"en": {
		"ATTR_STRENGTH": "Strength", "ATTR_AGILITY": "Agility", "ATTR_PERCEPTION": "Perception",
		"ATTR_VITALITY": "Vitality", "ATTR_WISDOM": "Wisdom",
		"FORM_SKELETON": "Skeleton", "FORM_ZOMBIE": "Zombie", "FORM_GHOUL": "Ghoul",
		"FORM_REVENANT": "Revenant", "FORM_ALMOST_HUMAN": "Almost Human",
		"TRAIT_SKELETON": "Immune to poison, fragile in melee",
		"TRAIT_ZOMBIE": "More health, but the body is still sluggish",
		"TRAIT_GHOUL": "Powerful attacks and access to equipment for the hands",
		"TRAIT_REVENANT": "Controls relics and holds more soul power",
		"TRAIT_ALMOST_HUMAN": "Can use a full set of human equipment",
		"SLOT_WEAPON": "Weapon", "SLOT_CHARM": "Charm", "SLOT_ARMOR": "Armor",
		"SLOT_HANDS": "Hands", "SLOT_RELIC": "Relic", "SLOT_OFFHAND": "Off hand",
		"ITEM_BONE_KNIFE": "Bone Knife", "ITEM_GRAVE_MACE": "Grave Mace",
		"ITEM_BONE_BOW": "Bone Bow",
		"ITEM_SOUL_LOCKET": "Soulcatcher Locket", "ITEM_ROTTING_MAIL": "Stitched Carapace",
		"ITEM_LEATHER_GLOVES": "Leather Gloves", "ITEM_HOLLOW_LANTERN": "Hollow Lantern",
		"ITEM_PILGRIM_SHIELD": "Pilgrim Shield",
		"CAMP_CRUSHER": "Crusher", "CAMP_WHETSTONE": "Whetstone",
		"CAMP_RITUAL_TABLE": "Ritual Table", "CAMP_CAMPFIRE": "Campfire",
		"ENEMY_GRAVE_RAT": "Grave Rat", "ENEMY_HOLLOW_GUARD": "Hollow Guard",
		"ENEMY_SOUL_LEECH": "Soul Leech", "ENEMY_SKELETAL_ARCHER": "Skeletal Archer",
		"ENEMY_MINOTAUR": "Minotaur",
		"GLYPH_GRAVE_RAT": "r", "GLYPH_HOLLOW_GUARD": "g", "GLYPH_SOUL_LEECH": "l",
		"GLYPH_SKELETAL_ARCHER": "a", "GLYPH_MINOTAUR": "M", "GLYPH_PLAYER": "P",
		"GLYPH_START": "S", "GLYPH_BASE": "B",
		"GLYPH_CHEST": "▣",
		"BTN_START": "Begin Expedition", "BTN_CHARACTER_ACTION": "Char. [E]",
		"BTN_INTERACT": "Action", "BTN_ASCEND": "Up [G]",
		"BTN_WAIT_ONE": "1 turn [T]", "BTN_WAIT_MANY": "%d turns [T]",
		"WAIT_CYCLE_HINT": "Cycle waiting: 1 → 10 → 100 turns",
		"BTN_AUTO_EXPLORE": "Auto [X]", "BTN_AUTO_EXPLORE_STOP": "Stop [X]",
		"BTN_ATTACK": "Attack [F]", "BTN_MAGIC": "Magic [Q]", "BTN_MAGIC_READY": "Missile [Q]",
		"BTN_CAMP": "Camp [R]",
		"BTN_CHEAT_ADD_STATS": "TEST: +5 POINTS",
		"BTN_UPGRADE": "Reinforce the Bone Hearth", "BTN_CHARACTER": "Character [E]",
		"BTN_CONTINUE": "Continue", "BTN_FINISH_CREATION": "Finish Creation",
		"BTN_BACK": "Return [Esc]", "BTN_LANGUAGE": "Language: %s", "BTN_MENU": "Menu",
		"BTN_NEW_GAME": "Start New Game", "BTN_NEW_GAME_CONFIRM": "Really start over?",
		"BTN_EXIT": "Exit Game", "BTN_EXIT_CONFIRM": "Really exit?",
		"SETTINGS_TITLE": "Settings", "SETTINGS_RADIUS": "Auto-inspection radius: %d cells",
		"SETTINGS_AUTO_DESC": "Without a selected target, the panel shows the nearest enemy.\nIf none are nearby, it shows an item or an important tile.",
		"BTN_SETTINGS_CLOSE": "Return [Esc]", "SETTINGS_WINDOWED": "Mode: Windowed",
		"SETTINGS_FULLSCREEN": "Mode: Fullscreen",
		"SETTINGS_INPUT_SUMMARY": "Keyboard and gamepad bindings can be changed.",
		"SETTINGS_SOUND_ON": "Sound: On", "SETTINGS_SOUND_OFF": "Sound: Off",
		"SETTINGS_BACKGROUND_VOLUME": "Background: %d%%", "SETTINGS_ACTIONS_VOLUME": "Actions: %d%%",
		"BTN_CONTROLS": "Configure Controls",
		"CONTROLS_TITLE": "Controls",
		"CONTROLS_SUBTITLE": "Select a binding, then press a new key or gamepad control.",
		"CONTROLS_ACTION_HEADER": "Action", "CONTROLS_KEYBOARD_HEADER": "Keyboard",
		"CONTROLS_GAMEPAD_HEADER": "Gamepad", "CONTROLS_BACK": "Return [Esc / B]",
		"CONTROLS_RESET": "Reset to Defaults", "CONTROLS_RESET_CONFIRM": "Confirm Reset",
		"CONTROLS_RESET_WARNING": "Press again to restore every default binding. Esc / B cancels.",
		"CONTROLS_RESET_DONE": "Default bindings restored.",
		"CONTROLS_NOT_ASSIGNED": "Not assigned",
		"CONTROLS_WAIT_KEYBOARD": "Waiting for a key… Esc cancels.",
		"CONTROLS_WAIT_GAMEPAD": "Waiting for a gamepad button or direction… B cancels.",
		"CONTROLS_WRONG_DEVICE": "Waiting for input from: %s.",
		"CONTROLS_CONFLICT": "%s is already assigned to: %s. Enter / A moves it here · Esc / B cancels.",
		"CONTROLS_APPLIED": "%s assigned to “%s”.",
		"CONTROLS_CANCELLED": "Change cancelled.",
		"CONTROLS_NAV_HINT": "Arrows / D-pad — select · Enter / A — change · Esc / B — back",
		"INPUT_ACTION_MOVE_UP": "Move Up", "INPUT_ACTION_MOVE_DOWN": "Move Down",
		"INPUT_ACTION_MOVE_LEFT": "Move Left", "INPUT_ACTION_MOVE_RIGHT": "Move Right",
		"INPUT_ACTION_ATTACK": "Primary Attack", "INPUT_ACTION_CAST_SPELL": "Active Slot 1",
		"INPUT_ACTION_WAIT": "Wait a Turn", "INPUT_ACTION_AUTO_EXPLORE": "Explore Floor",
		"INPUT_ACTION_CAMP": "Camp",
		"INPUT_ACTION_ASCEND": "Route to Stairs", "INPUT_ACTION_INTERACT": "Interact",
		"INPUT_ACTION_CHARACTER": "Character Sheet", "INPUT_ACTION_MENU": "Menu / Back",
		"INPUT_KEY_SPACE": "Space", "INPUT_KEY_ENTER": "Enter", "INPUT_KEY_ESCAPE": "Esc",
		"INPUT_KEY_TAB": "Tab", "INPUT_KEY_BACKSPACE": "Backspace",
		"INPUT_PAD_BACK": "Back", "INPUT_PAD_START": "Start", "INPUT_PAD_BUTTON": "Button %d",
		"INPUT_DPAD_DIRECTION": "D-pad %s", "INPUT_LEFT_STICK_DIRECTION": "Left stick %s",
		"INPUT_RIGHT_STICK_DIRECTION": "Right stick %s", "INPUT_PAD_AXIS": "Axis %d %s",
		"EXPEDITION_CHOICE_TITLE": "Where should the expedition begin?",
		"EXPEDITION_CHOICE_DESC": "The rope leads to the best floor you have safely returned from. Starting over lets a weakened body gather strength again.",
		"BTN_ASCEND_ROPE": "Climb the rope — level %d",
		"BTN_ASCEND_ROPE_LOCKED": "The rope is not anchored yet",
		"BTN_ASCEND_BEGINNING": "Begin the ascent from level %d",
		"TITLE_NAME_CREATION": "Character Creation — Name",
		"TITLE_STAT_CREATION": "Character Creation — Soul Pattern",
		"NAME_PROMPT": "What was this creature called in life?", "NAME_PLACEHOLDER": "Enter a name",
		"NAME_EMPTY": "The name cannot be empty.", "FREE_POINTS": "Free points: %d",
		"SKELETON_PARAMETERS": "Skeleton Parameters",
		"PARAM_DAMAGE": "Damage", "PARAM_ACCURACY": "Accuracy", "PARAM_HP": "HP",
		"PARAM_DODGE": "Dodge", "PARAM_MANA": "Mana", "PARAM_MANA_REGENERATION": "Mana regeneration",
		"PARAM_SPELL_POWER": "Spell Power",
		"PARAM_REGENERATION": "Regeneration", "PARAM_RANGED_DAMAGE": "Ranged Damage",
		"PARAM_RANGED_RANGE": "Ranged Range", "PARAM_VISION": "Vision",
		"PRIMARY_ATTRIBUTES": "PRIMARY ATTRIBUTES", "PARAMETERS": "PARAMETERS",
		"EQUIPMENT": "EQUIPMENT", "FORM_TRAIT": "FORM TRAIT",
		"MSG_AWAKENS": "%s awakens at the Bone Hearth.",
		"MSG_CHECKPOINT": "Level %d bone anchor activated.",
		"MSG_ENTER_FLOOR": "You enter level %d. The way to the surface lies ahead.",
		"MSG_SAFE_RETURN": "Safe return. Souls delivered to storage: %d.",
		"MSG_NOTHING_TO_USE": "There is nothing to use here. Find a Cradle, stairs or the path to base.",
		"MSG_BASE_UPGRADED": "The Bone Hearth reaches level %d. Maximum health increased.",
		"MSG_UPGRADE_NEEDS": "The upgrade requires %d souls.",
		"MSG_WAIT": "You stand still and let the enemies act.",
		"MSG_WAIT_COMPLETED": "Waiting complete: %d turns.",
		"MSG_WAIT_INTERRUPTED": "Waiting stopped after %d turns: an enemy was spotted.",
		"MSG_WAIT_INTERRUPTED_HP": "Waiting stopped after %d turns: health began to fall.",
		"MSG_WAIT_INTERRUPTED_RANGED": "Waiting stopped after %d turns: an arrow passed nearby.",
		"MSG_EXPLORE_ENEMY": "Exploration stopped: an enemy was spotted.",
		"MSG_EXPLORE_COMPLETE": "Every accessible part of the floor has been explored.",
		"MSG_EXPLORE_CANCELLED": "Automatic exploration stopped.",
		"MSG_EXPLORE_INTERRUPTED": "Exploration stopped: the route changed.",
		"MSG_ASCEND_LOCKED": "Find the stairs leading upward first.",
		"MSG_EXIT_DISCOVERED": "You discover the stairs leading upward.",
		"MSG_ASCEND_NO_PATH": "No safe route to the stairs could be found.",
		"MSG_ASCEND_STARTED": "You head for the stairs. The route will take %d turns.",
		"MSG_ASCEND_ARRIVED": "You reach the stairs. Use ascend again to enter the next level.",
		"MSG_ASCEND_INTERRUPTED": "Movement toward the stairs was interrupted.",
		"MSG_VICTORY": "You reach the first level. Beyond the door: light, and the question of what remains human.",
		"MSG_WALL": "The stone does not yield.",
		"MSG_BOSS_DOOR_LOCKED": "The heavy door is sealed by the Minotaur's power.",
		"MSG_BOSS_DOOR_OPEN": " The door beyond the arena opens.",
		"MSG_PLAYER_MISS": "Missed %s (%d vs %d).",
		"MSG_ENEMY_KILLED": "%s destroyed. Souls gained: %d.",
		"MSG_PLAYER_HIT": "Hit %s: %d health remains.",
		"MSG_ENEMY_MISS": " %s misses (%d vs %d).", "MSG_ENEMY_HIT": " %s deals %d damage.",
		"MSG_RANGED_NO_TARGET": "No visible target within %d cells for a shot.",
		"MSG_RANGED_TARGET_HIDDEN": "The selected target is hidden by the fog of war.",
		"MSG_RANGED_OUT_OF_RANGE": "The selected target is beyond bow range (%d cells).",
		"MSG_RANGED_LINE_BLOCKED": "There is no clear line of fire to the selected target.",
		"MSG_PLAYER_RANGED_MISS": "The arrow misses %s (%d vs %d).",
		"MSG_PLAYER_RANGED_HIT": "The arrow hits %s for %d damage; %d HP remains.",
		"MSG_PLAYER_RANGED_KILLED": "The arrow destroys %s for %d damage; gained %d souls.",
		"MSG_ENEMY_RANGED_MISS": " %s fires an arrow and misses (%d vs %d).",
		"MSG_ENEMY_RANGED_HIT": " %s hits with an arrow for %d damage.",
		"MSG_HIDDEN_RANGED_MISS": " An arrow flies out of the darkness and misses.",
		"MSG_HIDDEN_RANGED_HIT": " An arrow from the darkness deals %d damage.",
		"MSG_ITEM_EQUIPPED": "Equipped: %s.",
		"MSG_MANA_REGENERATED": " Mana regenerates: +%d.",
		"MSG_MAGIC_LOCKED": "Awaken magic and learn Magic Missile first.",
		"MSG_MAGIC_NO_MANA": "Magic Missile requires %d mana.",
		"MSG_MAGIC_OUT_OF_RANGE": "The selected target is beyond spell range (%d cells).",
		"MSG_MAGIC_LINE_BLOCKED": "A wall blocks the line to the selected target.",
		"MSG_MAGIC_NO_TARGET": "No Magic Missile target within %d cells.",
		"MSG_MAGIC_HIT": "Magic Missile hits %s for %d damage; %d HP remains.",
		"MSG_MAGIC_KILLED": "Magic Missile destroys %s for %d damage; gained %d souls.",
		"MSG_MAGIC_RICOCHET": " Ricochet — %s",
		"MSG_ITEM_UNEQUIPPED": "Unequipped and returned to inventory: %s.",
		"MSG_FORM_CANNOT_EQUIP_SELECTED": "The current form cannot use this slot.",
		"MSG_CHEST_OPENED": "Chest opened: %s · wood +%d · stone +%d.",
		"MSG_ITEM_DISMANTLED": "%s dismantled: wood +%d · stone +%d · cloth +%d.",
		"MSG_CRUSHER_REQUIRED": "An installed Crusher at base is required to dismantle items.",
		"MSG_WHETSTONE_REQUIRED": "An installed Whetstone at base is required to upgrade weapons.",
		"MSG_WEAPON_UPGRADED": "Upgrade succeeded: the weapon is now +%d.",
		"MSG_WEAPON_DOWNGRADED": "Failure damaged the weapon: its level fell to +%d.",
		"MSG_WEAPON_UNCHANGED": "The upgrade failed, but the weapon was unharmed.",
		"MSG_WEAPON_UPGRADE_RESOURCES": "An attempt requires %d stone, %d wood and %d cloth.",
		"MSG_ITEM_BOUND": "%s is now bound to the hero for %d souls and will survive death.",
		"MSG_ITEM_ALREADY_BOUND": "This item is already bound to the hero.",
		"MSG_ITEM_BIND_NEEDS_SOULS": "The ritual requires %d souls.",
		"MSG_RITUAL_TABLE_REQUIRED": "Binding is available only at a built Ritual Table.",
		"MSG_BOUND_ITEM_CANNOT_DISMANTLE": "A bound item cannot be dismantled.",
		"MSG_ITEMS_DISMANTLED_ALL": "Dismantled %d items · wood +%d · stone +%d · cloth +%d.",
		"MSG_DEATH": "The body is destroyed. Lost souls: %d, items: %d. You are a skeleton again.",
		"MSG_PATH_BASE": "The way down is open. Return to base to secure free souls.",
		"MSG_PATH_UP": "The stairs lead toward the surface, to level %d.",
		"MSG_TILE_START": "Level entry point.", "MSG_TURN_DONE": "Turn complete. Enemies draw closer.",
		"MSG_UNKNOWN_ITEM": "Unknown item.", "MSG_FORM_CANNOT_USE": "%s cannot yet use %s.",
		"MSG_GAME_LOADED": "Save loaded. You return to the Bone Hearth.",
		"MSG_NO_ADJACENT_ENEMY": "There is no adjacent target to attack.",
		"MSG_ABILITY_SLOT_EMPTY": "No active ability is assigned to this slot.",
		"MSG_ABILITY_FORM_LOCKED": "The current form cannot use this ability yet.",
		"MSG_ABILITY_CANCELLED": "Target selection cancelled.",
		"MSG_DASH_NO_TARGET": "There is no free explored route for Dash.",
		"MSG_DASH_TARGETING": "Dash: choose a highlighted cell. Hold two directions for a diagonal; Enter confirms, Esc cancels.",
		"MSG_DASH_INVALID": "Dash cannot reach that cell.",
		"MSG_DASH_COMPLETE": "Dash complete: moved %d cells.",
		"MSG_DASH_CHEST": " The chest was collected only at the Dash endpoint.",
		"MSG_ENEMY_DASH": " %s dashes and stops nearby.",
		"MSG_DOUBLE_ATTACK_SECOND": " Second strike: %s",
		"MSG_PASSIVE_DOUBLE_STRIKE": " Follow-up strike: %s",
		"MSG_CIRCULAR_ATTACK": "Circular Attack strikes every nearby enemy.",
		"MSG_CIRCULAR_NO_TARGETS": "There are no nearby targets for Circular Attack.",
		"MSG_EXIT_BLOCKED": "The stairs leading upward have not been discovered yet.",
		"MSG_FOOD_GAINED": " Food gained: %d.",
		"MSG_CAMP_EAT": "You make camp and eat 1 food. Hunger: %d%%.",
		"MSG_CAMP_NO_FOOD": "You need meat supplies to eat at camp.",
		"MSG_CAMP_FULL": "The flesh is already satiated.", "MSG_CAMP_SKELETON": "A skeleton has nothing to feed.",
		"MSG_HUNGER_TICK": " Hunger: %d%%.", "MSG_REGENERATED": " Regeneration restores %d HP.",
		"MSG_STARVATION": " Starvation ravages the body: %d HP lost.",
		"MSG_CRADLE_APPEARED": "A Cradle was found on this floor.",
		"MSG_CRADLE_REQUIRED": "The body can only change inside a Cradle.",
		"MSG_CRADLE_TILE": "A Cradle stands before you. The next body stage can be purchased here.",
		"MSG_CRADLE_USED": "This Cradle has already reshaped the body and now lies silent.",
		"MSG_CRADLE_MAX": "The Cradle cannot improve the final form.",
		"MSG_CRADLE_NEEDS_SOULS": "The next stage requires %d carried souls.",
		"MSG_CRADLE_EVOLVED": "The Cradle reshapes the body into %s, consuming %d souls.",
		"CRADLE_CONFIRM_TITLE": "Confirm Evolution",
		"CRADLE_CONFIRM_DESC": "%s → %s\nCost: %d carried souls\nCarried: %d souls",
		"CRADLE_CONFIRM_BUTTON": "Evolve — %d souls",
		"CRADLE_CONFIRM_CANCEL": "Keep the current form",
		"CRADLE_CONFIRM_UNAVAILABLE": "Evolution unavailable",
		"BOSS_WARNING_TITLE": "Ascend further?",
		"BOSS_WARNING_DESC": "You sense a powerful soul beyond the stairs.\nContinue the ascent to level %d?",
		"BOSS_WARNING_CONFIRM": "Ascend to level %d",
		"BOSS_WARNING_CANCEL": "Stay and prepare",
		"SIDEBAR_HUNGER": "Hunger: %d%%", "SIDEBAR_FOOD": "Food: %d",
		"CHARACTER_SURVIVAL": "Hunger: %d%% · Food: %d",
		"SKILLS_TITLE": "SKILLS", "SKILL_TAB_SKELETON": "Skeleton", "SKILL_TAB_ZOMBIE": "Zombie",
		"SKILL_TAB_GHOUL": "Ghoul", "SKILL_TAB_REVENANT": "Revenant",
		"SKILL_TAB_ALMOST_HUMAN": "Almost Human",
		"SKILL_TAB_LOCKED": "%s 🔒", "SKILL_LEVEL": "Lv. %d/%d", "SKILL_COST": "Cost: %d souls",
		"SKILL_KIND_ACTIVE": "ACTIVE · square", "SKILL_KIND_PASSIVE": "PASSIVE · circle",
		"SKILL_MAX": "Maximum level", "SKILL_COMING_SOON": "COMING SOON\nEmpty node",
		"SKILL_STRONG_BONES": "Sturdy Bones", "SKILL_STRONG_BONES_DESC": "+3 maximum HP per level",
		"SKILL_FUNDAMENTALS": "Develop Fundamentals", "SKILL_FUNDAMENTALS_DESC": "+5 free attribute points",
		"SKILL_MAGIC_AWAKENING": "Magic Awakening", "SKILL_MAGIC_AWAKENING_DESC": "+5 mana and access to the magic branch",
		"SKILL_MAGIC_MISSILE": "Magic Missile", "SKILL_MAGIC_MISSILE_DESC": "10 mana · 3 damage +1/lvl · range 3",
		"SKILL_MAGIC_MISSILE_RANGE": "Long Missile", "SKILL_MAGIC_MISSILE_RANGE_DESC": "+2 cells of Magic Missile range",
		"SKILL_MAGIC_RICOCHET": "Ricochet", "SKILL_MAGIC_RICOCHET_DESC": "20% +5%/lvl · jumps to an enemy within 4",
		"SKILL_FLESH_REGENERATION": "Regeneration", "SKILL_FLESH_REGENERATION_DESC": "Activates healing from regeneration (zombie base: +1)",
		"SKILL_SHARP_VISION": "Sharp Vision", "SKILL_SHARP_VISION_DESC": "+1 vision cell per level",
		"SKILL_DASH": "Dash", "SKILL_DASH_DESC": "Move 1–3 cells in a straight line, including diagonals",
		"SKILL_DOUBLE_ATTACK": "Double Attack", "SKILL_DOUBLE_ATTACK_DESC": "Two independent strikes against one target in one turn",
		"SKILL_ALMOST_DOUBLE_STRIKE": "Follow-up Strike", "SKILL_ALMOST_DOUBLE_STRIKE_DESC": "10% +2 pp/lvl to repeat a basic attack",
		"SKILL_CIRCULAR_ATTACK": "Circular Attack", "SKILL_CIRCULAR_ATTACK_DESC": "A separate strike into all 8 adjacent cells",
		"SKILL_SOULS": "Souls available: %d", "SKILL_FREE_STATS": "Free stats: %d",
		"ABILITY_BASIC_ATTACK": "Basic Attack", "ABILITY_BASIC_SHOT": "Basic Shot",
		"ABILITY_MAGIC_MISSILE": "Magic Missile",
		"ABILITY_DASH": "Dash", "ABILITY_DOUBLE_ATTACK": "Double Attack",
		"ABILITY_CIRCULAR_ATTACK": "Circular Attack", "ABILITY_EMPTY": "Empty",
		"ABILITY_SLOT_ATTACK": "Primary Attack", "ABILITY_SLOT_ACTIVE_1": "Active 1",
		"ABILITY_SLOT_ACTIVE_2": "Active 2", "ABILITY_SLOT_ACTIVE_3": "Active 3",
		"ABILITY_ASSIGN_HINT": "Press to cycle through learned compatible abilities.",
		"ABILITY_ASSIGNED": "%s: assigned %s.",
		"ABILITY_HOTBAR_TOOLTIP": "%s · %s",
		"SKILL_BASE_ONLY": "Free attribute points can only be spent at base.",
		"SKILL_PURCHASED": "Skill %s increased to level %d.",
		"SKILL_NEEDS_SOULS": "The skill requires %d souls.",
		"SKILL_NEEDS_PREVIOUS": "Learn the previous skill first.",
		"SKILL_STAGE_LOCKED": "Reach this body stage first.",
		"SKILL_ALREADY_MAX": "The skill is already fully developed.",
		"EVOLUTION_MAX": "Final form reached",
		"EVOLUTION_NEXT": "%s · %d souls at a Cradle",
		"TITLE_FLOOR": "Level %d — path to the surface", "TITLE_BASE": "Level 100 — Bone Hearth",
		"TITLE_EXIT": "Level 1 — Exit",
		"HINT_DUNGEON": "WASD — move  |  F — primary attack  |  Q — active 1  |  T — wait  |  G — stairs",
		"HINT_BASE": "Stored souls are safe. Form and equipment persist until death.",
		"HINT_END": "End of the vertical slice", "SIDEBAR_FORM": "Form: %s",
		"SIDEBAR_HP": "Health: %d/%d", "SIDEBAR_CARRIED": "Free souls: %d",
		"SIDEBAR_BANKED": "Souls at base: %d", "SIDEBAR_EVOLUTION": "Evolution: %s",
		"SIDEBAR_SOULS_COMBINED": "Souls: carried %d · at base %d",
		"SOUL_COUNTER": "Souls: %d (%d total)",
		"SIDEBAR_CRADLE_CHANCE": "Next Cradle chance: %d%%",
		"SIDEBAR_EQUIPMENT": "Equipment:", "UPGRADE_COST": "Reinforce hearth — %d souls",
		"CAMP_RESOURCES": "Materials: wood %d · stone %d · cloth %d",
		"CAMP_MATERIAL_HINT": "Wood and stone come from chests; cloth comes from dismantled armor.",
		"CAMP_INSTALLED": "Installed upgrades:", "CAMP_INSTALLED_NONE": "none yet",
		"CAMP_BUILD_CRUSHER": "Build Crusher — 5 wood · 5 stone",
		"CAMP_BUILD_WHETSTONE": "Install Whetstone — 10 wood · 10 stone · 5 cloth",
		"CAMP_BUILD_RITUAL_TABLE": "Build Ritual Table — 10 wood · 10 stone · 5 cloth",
		"CAMP_BUILD_CAMPFIRE": "Build Campfire — 3 wood · 3 stone · +1 HP",
		"CAMP_BUILT_CRUSHER": "Crusher installed", "CAMP_BUILT_WHETSTONE": "Whetstone installed",
		"CAMP_BUILT_RITUAL_TABLE": "Ritual Table installed",
		"CAMP_BUILT_CAMPFIRE": "Campfire built · +1 HP",
		"MSG_CAMP_UPGRADE_BUILT": "Camp upgrade installed: %s.",
		"MSG_CAMP_UPGRADE_NEEDS": "Not enough materials to build this upgrade.",
		"MSG_CAMP_UPGRADE_EXISTS": "This upgrade is already installed.",
		"CHARACTER_TAB_SKILLS": "Skills", "CHARACTER_TAB_INVENTORY": "Inventory",
		"INVENTORY_SLOT_LOCKED": "locked", "INVENTORY_SELECT_ITEM": "Select an item or occupied slot.",
		"INVENTORY_PAGE": "Page %d / %d", "INVENTORY_EQUIP": "Equip",
		"INVENTORY_UNEQUIP": "Unequip", "INVENTORY_DISMANTLE": "Dismantle",
		"INVENTORY_DISMANTLE_ALL": "Dismantle all",
		"INVENTORY_DISMANTLE_ALL_CONFIRM_BUTTON": "Really all?",
		"INVENTORY_DISMANTLE_ALL_CONFIRM": "Press again to dismantle every unbound inventory item. Equipped and bound gear stays.",
		"INVENTORY_UPGRADE": "Upgrade weapon", "INVENTORY_UPGRADE_MAX": "Maximum upgrade +3",
		"INVENTORY_UPGRADE_WEAPON_ONLY": "Only weapons can be upgraded",
		"INVENTORY_UPGRADE_SELECT_SHORT": "Select weapon",
		"INVENTORY_UPGRADE_CHANCE": "Upgrade to +%d · %d%% chance",
		"INVENTORY_UPGRADE_CHANCE_COST": "To +%d · %d%% · %d stone, %d wood, %d cloth",
		"INVENTORY_ITEM_DETAIL": "Slot: %s\nDamage: %d · Accuracy: %d · HP: %d · Mana: %d",
		"INVENTORY_RANGED_ITEM_DETAIL": "Slot: %s\nRanged damage: %d · Accuracy: %d · Range: %d\nHP: %d · Mana: %d",
		"INVENTORY_FILTER_ALL": "All", "INVENTORY_EMPTY_FILTER": "No items in this category",
		"INVENTORY_SELECTED_PANEL": "SELECTED ITEM", "INVENTORY_EQUIPPED_PANEL": "EQUIPPED IN SLOT",
		"INVENTORY_EMPTY": "Empty", "INVENTORY_SLOT_LINE": "Slot: %s",
		"INVENTORY_LEVEL": "Upgrade: +%d", "INVENTORY_COUNT": "Count: ×%d",
		"INVENTORY_SALVAGE": "Salvage: wood %d · stone %d · cloth %d",
		"INVENTORY_SOUL_BONUS": "Soul bonus",
		"INVENTORY_SOURCE_INVENTORY": "Inventory", "INVENTORY_SOURCE_EQUIPPED": "Equipped",
		"INVENTORY_SOURCE_LOCKED": "Locked slot",
		"INVENTORY_SERVICE_CRUSHER": "CRUSHER · ITEM DISMANTLING",
		"INVENTORY_SERVICE_WHETSTONE": "WHETSTONE · WEAPONS",
		"INVENTORY_SERVICE_RITUAL": "RITUAL TABLE · ITEM BINDING",
		"INVENTORY_BOUND_STATUS": "Bound to the hero · survives death",
		"INVENTORY_BOUND_SHORT": "bound",
		"INVENTORY_BIND_EXPLANATION": "The ritual binds one item instance to the hero. It will not be lost on death.",
		"INVENTORY_BIND_ACTION": "Bind — %d souls",
		"INVENTORY_BIND_ALREADY": "Already bound",
		"INVENTORY_BIND_TOOLTIP": "Bind one item instance to the hero for %d souls",
		"INVENTORY_BIND_ALREADY_DESC": "This item will already survive death",
		"INVENTORY_REASON_MAX": "This weapon is already upgraded to +3.",
		"INVENTORY_REASON_RESOURCES": "Requires 10 stone, 2 wood and 1 cloth.",
		"INVENTORY_PREVIOUS_PAGE": "Previous page", "INVENTORY_NEXT_PAGE": "Next page",
		"CAMP_OBJECT_CRUSHER": "Crusher\nOpen [Enter / A]",
		"CAMP_OBJECT_CRUSHER_TOOLTIP": "Open the item dismantling service",
		"CAMP_OBJECT_WHETSTONE": "Whetstone\nOpen [Enter / A]",
		"CAMP_OBJECT_WHETSTONE_TOOLTIP": "Open the weapon upgrade service",
		"CAMP_OBJECT_RITUAL_TABLE": "Ritual Table\nOpen [Enter / A]",
		"CAMP_OBJECT_RITUAL_TABLE_TOOLTIP": "Open the item binding service",
		"MAGIC_MISSILE_TOOLTIP": "Damage %d · range %d · %d mana · 100%% hit · requires line of sight",
		"MAGIC_LOCKED_TOOLTIP": "Unlocked by the Magic Missile skill",
		"BASE_CENTER": "BONE HEARTH", "BASE_SUBTITLE": "Every new body begins here",
		"STORY_INTRO_1": "The skeleton wandered the lower levels for a long time, remembering neither name nor purpose.",
		"STORY_INTRO_2": "The first thing it found was an old poncho—almost absurd, but finally something of its own.",
		"STORY_INTRO_3": "Then something answered from inside the empty rib cage.",
		"STORY_DEATH": "After a time, the remains fell through the hatch into the quiet refuge below.",
		"STORY_CONTINUE": "Click to continue",
		"EXIT_CENTER": "LIGHT FROM THE SURFACE",
		"INSPECT_HEADER_AUTO": "INSPECTION · AUTO", "INSPECT_HEADER_SELECTED": "INSPECTION · SELECTED",
		"INSPECT_NONE": "Nothing interesting within %d cells.",
		"INSPECT_TARGET": "%s · %d cells",
		"INSPECT_ENEMY_STATS": "HP %d/%d · Damage %d · Accuracy %d · Vision %d",
		"INSPECT_ITEM_STATS": "Slot: %s · Damage %d · HP %d",
		"INSPECT_CHEST": "Chest", "INSPECT_CHEST_DESC": "Contains an item and possibly wood or stone.",
		"INSPECT_BASE": "Descent to base", "INSPECT_EXIT": "Stairs toward the surface",
		"INSPECT_START": "Level entry", "INSPECT_WALL": "Stone wall",
		"INSPECT_BOSS_DOOR": "Sealed arena door",
		"INSPECT_BOSS_DOOR_OPEN": "Open arena door",
		"INSPECT_CRADLE": "Cradle", "INSPECT_CRADLE_READY": "Next form: %s · Cost: %d souls",
		"INSPECT_CRADLE_USED": "This floor's transformation has already been used",
		"INSPECT_FLOOR": "Stone floor", "INSPECT_VOID": "Impassable void",
	},
}

static var current_locale := "ru"
static var initialized := false


static func initialize_from_system() -> void:
	if initialized:
		return
	var system_locale := OS.get_locale_language().to_lower()
	current_locale = "en" if system_locale == "en" else "ru"
	initialized = true


static func toggle_locale() -> void:
	current_locale = "en" if current_locale == "ru" else "ru"
	initialized = true


static func set_locale(locale: String) -> void:
	if SUPPORTED_LOCALES.has(locale):
		current_locale = locale
		initialized = true


static func text(key: String, arguments: Array = []) -> String:
	var locale_strings: Dictionary = STRINGS.get(current_locale, STRINGS["ru"])
	var fallback_strings: Dictionary = STRINGS["ru"]
	var template := String(locale_strings.get(key, fallback_strings.get(key, key)))
	if arguments.is_empty():
		return template
	return template % arguments


static func language_code() -> String:
	return current_locale.to_upper()
